/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9 */

#if defined(DRAGINO_OTA_LAB)

#include "draginoota.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(temeshtastic_DraginoOtaPacket, temeshtastic_DraginoOtaPacket, AUTO)


PB_BIND(temeshtastic_DraginoOtaPacket_DownlinkPacket, temeshtastic_DraginoOtaPacket_DownlinkPacket, AUTO)


PB_BIND(temeshtastic_DraginoOtaPacket_DownlinkPacket_Begin, temeshtastic_DraginoOtaPacket_DownlinkPacket_Begin, AUTO)


PB_BIND(temeshtastic_DraginoOtaPacket_DownlinkPacket_Chunk, temeshtastic_DraginoOtaPacket_DownlinkPacket_Chunk, AUTO)


PB_BIND(temeshtastic_DraginoOtaPacket_DownlinkPacket_Finalize, temeshtastic_DraginoOtaPacket_DownlinkPacket_Finalize, AUTO)


PB_BIND(temeshtastic_DraginoOtaPacket_DownlinkPacket_Abort, temeshtastic_DraginoOtaPacket_DownlinkPacket_Abort, AUTO)


PB_BIND(temeshtastic_DraginoOtaPacket_DownlinkPacket_GetStatus, temeshtastic_DraginoOtaPacket_DownlinkPacket_GetStatus, AUTO)


PB_BIND(temeshtastic_DraginoOtaPacket_DownlinkPacket_Reboot, temeshtastic_DraginoOtaPacket_DownlinkPacket_Reboot, AUTO)


PB_BIND(temeshtastic_DraginoOtaPacket_UplinkPacket, temeshtastic_DraginoOtaPacket_UplinkPacket, AUTO)


PB_BIND(temeshtastic_DraginoOtaPacket_UplinkPacket_Ack, temeshtastic_DraginoOtaPacket_UplinkPacket_Ack, AUTO)


PB_BIND(temeshtastic_DraginoOtaPacket_UplinkPacket_Status, temeshtastic_DraginoOtaPacket_UplinkPacket_Status, AUTO)

#endif // DRAGINO_OTA_LAB





