/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9 */

#ifndef PB_TEMESHTASTIC_PROTOBUF_DRAGINOOTA_PB_H_INCLUDED
#define PB_TEMESHTASTIC_PROTOBUF_DRAGINOOTA_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _temeshtastic_DraginoOtaPacket_State {
    temeshtastic_DraginoOtaPacket_State_STATE_IDLE = 0,
    temeshtastic_DraginoOtaPacket_State_STATE_RECEIVING = 1,
    temeshtastic_DraginoOtaPacket_State_STATE_VERIFYING = 2,
    temeshtastic_DraginoOtaPacket_State_STATE_READY_TO_REBOOT = 3,
    temeshtastic_DraginoOtaPacket_State_STATE_FAILED = 4
} temeshtastic_DraginoOtaPacket_State;

typedef enum _temeshtastic_DraginoOtaPacket_StatusCode {
    temeshtastic_DraginoOtaPacket_StatusCode_STATUS_UNKNOWN = 0,
    temeshtastic_DraginoOtaPacket_StatusCode_STATUS_OK = 1,
    temeshtastic_DraginoOtaPacket_StatusCode_STATUS_BAD_SESSION = 2,
    temeshtastic_DraginoOtaPacket_StatusCode_STATUS_BAD_IMAGE = 3,
    temeshtastic_DraginoOtaPacket_StatusCode_STATUS_BAD_OFFSET = 4,
    temeshtastic_DraginoOtaPacket_StatusCode_STATUS_BAD_CRC = 5,
    temeshtastic_DraginoOtaPacket_StatusCode_STATUS_FLASH_ERROR = 6,
    temeshtastic_DraginoOtaPacket_StatusCode_STATUS_VERIFY_FAILED = 7,
    temeshtastic_DraginoOtaPacket_StatusCode_STATUS_UNSUPPORTED = 8,
    temeshtastic_DraginoOtaPacket_StatusCode_STATUS_BUSY = 9,
    temeshtastic_DraginoOtaPacket_StatusCode_STATUS_NOT_READY = 10,
    temeshtastic_DraginoOtaPacket_StatusCode_STATUS_NOT_AUTHORIZED = 11
} temeshtastic_DraginoOtaPacket_StatusCode;

/* Struct definitions */
typedef PB_BYTES_ARRAY_T(32) temeshtastic_DraginoOtaPacket_DownlinkPacket_Begin_image_sha256_t;
typedef struct _temeshtastic_DraginoOtaPacket_DownlinkPacket_Begin {
    uint32_t session_id;
    uint32_t image_id;
    uint32_t image_size;
    uint32_t image_crc32;
    temeshtastic_DraginoOtaPacket_DownlinkPacket_Begin_image_sha256_t image_sha256;
    uint32_t chunk_size;
    uint32_t total_chunks;
    uint32_t firmware_version;
    uint32_t build_number;
    uint32_t min_bootloader_version;
    char target_hw_model[16];
    char target_app_profile[32];
    uint32_t flags;
} temeshtastic_DraginoOtaPacket_DownlinkPacket_Begin;

typedef PB_BYTES_ARRAY_T(192) temeshtastic_DraginoOtaPacket_DownlinkPacket_Chunk_data_t;
typedef struct _temeshtastic_DraginoOtaPacket_DownlinkPacket_Chunk {
    uint32_t session_id;
    uint32_t image_id;
    uint32_t chunk_index;
    uint32_t offset;
    temeshtastic_DraginoOtaPacket_DownlinkPacket_Chunk_data_t data;
    uint32_t chunk_crc32;
} temeshtastic_DraginoOtaPacket_DownlinkPacket_Chunk;

typedef struct _temeshtastic_DraginoOtaPacket_DownlinkPacket_Finalize {
    uint32_t session_id;
    uint32_t image_id;
    uint32_t manifest_slot;
    bool reboot_after_commit;
} temeshtastic_DraginoOtaPacket_DownlinkPacket_Finalize;

typedef struct _temeshtastic_DraginoOtaPacket_DownlinkPacket_Abort {
    uint32_t session_id;
    uint32_t image_id;
} temeshtastic_DraginoOtaPacket_DownlinkPacket_Abort;

typedef struct _temeshtastic_DraginoOtaPacket_DownlinkPacket_GetStatus {
    bool include_bootloader_status;
} temeshtastic_DraginoOtaPacket_DownlinkPacket_GetStatus;

typedef struct _temeshtastic_DraginoOtaPacket_DownlinkPacket_Reboot {
    uint32_t session_id;
    uint32_t image_id;
} temeshtastic_DraginoOtaPacket_DownlinkPacket_Reboot;

typedef struct _temeshtastic_DraginoOtaPacket_DownlinkPacket {
    pb_size_t which_payload;
    union {
        temeshtastic_DraginoOtaPacket_DownlinkPacket_Begin begin;
        temeshtastic_DraginoOtaPacket_DownlinkPacket_Chunk chunk;
        temeshtastic_DraginoOtaPacket_DownlinkPacket_Finalize finalize;
        temeshtastic_DraginoOtaPacket_DownlinkPacket_Abort abort;
        temeshtastic_DraginoOtaPacket_DownlinkPacket_GetStatus get_status;
        temeshtastic_DraginoOtaPacket_DownlinkPacket_Reboot reboot;
    } payload;
} temeshtastic_DraginoOtaPacket_DownlinkPacket;

typedef struct _temeshtastic_DraginoOtaPacket_UplinkPacket_Ack {
    uint32_t session_id;
    uint32_t image_id;
    uint32_t chunk_index;
    temeshtastic_DraginoOtaPacket_StatusCode status;
    char message[48];
} temeshtastic_DraginoOtaPacket_UplinkPacket_Ack;

typedef struct _temeshtastic_DraginoOtaPacket_UplinkPacket_Status {
    uint32_t session_id;
    uint32_t image_id;
    temeshtastic_DraginoOtaPacket_State state;
    uint32_t image_size;
    uint32_t written_size;
    uint32_t next_offset;
    uint32_t last_error;
    uint32_t bootloader_status;
    uint32_t bootloader_detail;
    uint32_t bootloader_sequence;
    uint32_t bootloader_image_id;
} temeshtastic_DraginoOtaPacket_UplinkPacket_Status;

typedef struct _temeshtastic_DraginoOtaPacket_UplinkPacket {
    pb_size_t which_payload;
    union {
        temeshtastic_DraginoOtaPacket_UplinkPacket_Ack ack;
        temeshtastic_DraginoOtaPacket_UplinkPacket_Status status;
    } payload;
} temeshtastic_DraginoOtaPacket_UplinkPacket;

typedef struct _temeshtastic_DraginoOtaPacket {
    pb_size_t which_packet_type;
    union {
        temeshtastic_DraginoOtaPacket_DownlinkPacket downlink_packet;
        temeshtastic_DraginoOtaPacket_UplinkPacket uplink_packet;
    } packet_type;
} temeshtastic_DraginoOtaPacket;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _temeshtastic_DraginoOtaPacket_State_MIN temeshtastic_DraginoOtaPacket_State_STATE_IDLE
#define _temeshtastic_DraginoOtaPacket_State_MAX temeshtastic_DraginoOtaPacket_State_STATE_FAILED
#define _temeshtastic_DraginoOtaPacket_State_ARRAYSIZE ((temeshtastic_DraginoOtaPacket_State)(temeshtastic_DraginoOtaPacket_State_STATE_FAILED+1))

#define _temeshtastic_DraginoOtaPacket_StatusCode_MIN temeshtastic_DraginoOtaPacket_StatusCode_STATUS_UNKNOWN
#define _temeshtastic_DraginoOtaPacket_StatusCode_MAX temeshtastic_DraginoOtaPacket_StatusCode_STATUS_NOT_AUTHORIZED
#define _temeshtastic_DraginoOtaPacket_StatusCode_ARRAYSIZE ((temeshtastic_DraginoOtaPacket_StatusCode)(temeshtastic_DraginoOtaPacket_StatusCode_STATUS_NOT_AUTHORIZED+1))










#define temeshtastic_DraginoOtaPacket_UplinkPacket_Ack_status_ENUMTYPE temeshtastic_DraginoOtaPacket_StatusCode

#define temeshtastic_DraginoOtaPacket_UplinkPacket_Status_state_ENUMTYPE temeshtastic_DraginoOtaPacket_State


/* Initializer values for message structs */
#define temeshtastic_DraginoOtaPacket_init_default {0, {temeshtastic_DraginoOtaPacket_DownlinkPacket_init_default}}
#define temeshtastic_DraginoOtaPacket_DownlinkPacket_init_default {0, {temeshtastic_DraginoOtaPacket_DownlinkPacket_Begin_init_default}}
#define temeshtastic_DraginoOtaPacket_DownlinkPacket_Begin_init_default {0, 0, 0, 0, {0, {0}}, 0, 0, 0, 0, 0, "", "", 0}
#define temeshtastic_DraginoOtaPacket_DownlinkPacket_Chunk_init_default {0, 0, 0, 0, {0, {0}}, 0}
#define temeshtastic_DraginoOtaPacket_DownlinkPacket_Finalize_init_default {0, 0, 0, 0}
#define temeshtastic_DraginoOtaPacket_DownlinkPacket_Abort_init_default {0, 0}
#define temeshtastic_DraginoOtaPacket_DownlinkPacket_GetStatus_init_default {0}
#define temeshtastic_DraginoOtaPacket_DownlinkPacket_Reboot_init_default {0, 0}
#define temeshtastic_DraginoOtaPacket_UplinkPacket_init_default {0, {temeshtastic_DraginoOtaPacket_UplinkPacket_Ack_init_default}}
#define temeshtastic_DraginoOtaPacket_UplinkPacket_Ack_init_default {0, 0, 0, _temeshtastic_DraginoOtaPacket_StatusCode_MIN, ""}
#define temeshtastic_DraginoOtaPacket_UplinkPacket_Status_init_default {0, 0, _temeshtastic_DraginoOtaPacket_State_MIN, 0, 0, 0, 0, 0, 0, 0, 0}
#define temeshtastic_DraginoOtaPacket_init_zero  {0, {temeshtastic_DraginoOtaPacket_DownlinkPacket_init_zero}}
#define temeshtastic_DraginoOtaPacket_DownlinkPacket_init_zero {0, {temeshtastic_DraginoOtaPacket_DownlinkPacket_Begin_init_zero}}
#define temeshtastic_DraginoOtaPacket_DownlinkPacket_Begin_init_zero {0, 0, 0, 0, {0, {0}}, 0, 0, 0, 0, 0, "", "", 0}
#define temeshtastic_DraginoOtaPacket_DownlinkPacket_Chunk_init_zero {0, 0, 0, 0, {0, {0}}, 0}
#define temeshtastic_DraginoOtaPacket_DownlinkPacket_Finalize_init_zero {0, 0, 0, 0}
#define temeshtastic_DraginoOtaPacket_DownlinkPacket_Abort_init_zero {0, 0}
#define temeshtastic_DraginoOtaPacket_DownlinkPacket_GetStatus_init_zero {0}
#define temeshtastic_DraginoOtaPacket_DownlinkPacket_Reboot_init_zero {0, 0}
#define temeshtastic_DraginoOtaPacket_UplinkPacket_init_zero {0, {temeshtastic_DraginoOtaPacket_UplinkPacket_Ack_init_zero}}
#define temeshtastic_DraginoOtaPacket_UplinkPacket_Ack_init_zero {0, 0, 0, _temeshtastic_DraginoOtaPacket_StatusCode_MIN, ""}
#define temeshtastic_DraginoOtaPacket_UplinkPacket_Status_init_zero {0, 0, _temeshtastic_DraginoOtaPacket_State_MIN, 0, 0, 0, 0, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define temeshtastic_DraginoOtaPacket_DownlinkPacket_Begin_session_id_tag 1
#define temeshtastic_DraginoOtaPacket_DownlinkPacket_Begin_image_id_tag 2
#define temeshtastic_DraginoOtaPacket_DownlinkPacket_Begin_image_size_tag 3
#define temeshtastic_DraginoOtaPacket_DownlinkPacket_Begin_image_crc32_tag 4
#define temeshtastic_DraginoOtaPacket_DownlinkPacket_Begin_image_sha256_tag 5
#define temeshtastic_DraginoOtaPacket_DownlinkPacket_Begin_chunk_size_tag 6
#define temeshtastic_DraginoOtaPacket_DownlinkPacket_Begin_total_chunks_tag 7
#define temeshtastic_DraginoOtaPacket_DownlinkPacket_Begin_firmware_version_tag 8
#define temeshtastic_DraginoOtaPacket_DownlinkPacket_Begin_build_number_tag 9
#define temeshtastic_DraginoOtaPacket_DownlinkPacket_Begin_min_bootloader_version_tag 10
#define temeshtastic_DraginoOtaPacket_DownlinkPacket_Begin_target_hw_model_tag 11
#define temeshtastic_DraginoOtaPacket_DownlinkPacket_Begin_target_app_profile_tag 12
#define temeshtastic_DraginoOtaPacket_DownlinkPacket_Begin_flags_tag 13
#define temeshtastic_DraginoOtaPacket_DownlinkPacket_Chunk_session_id_tag 1
#define temeshtastic_DraginoOtaPacket_DownlinkPacket_Chunk_image_id_tag 2
#define temeshtastic_DraginoOtaPacket_DownlinkPacket_Chunk_chunk_index_tag 3
#define temeshtastic_DraginoOtaPacket_DownlinkPacket_Chunk_offset_tag 4
#define temeshtastic_DraginoOtaPacket_DownlinkPacket_Chunk_data_tag 5
#define temeshtastic_DraginoOtaPacket_DownlinkPacket_Chunk_chunk_crc32_tag 6
#define temeshtastic_DraginoOtaPacket_DownlinkPacket_Finalize_session_id_tag 1
#define temeshtastic_DraginoOtaPacket_DownlinkPacket_Finalize_image_id_tag 2
#define temeshtastic_DraginoOtaPacket_DownlinkPacket_Finalize_manifest_slot_tag 3
#define temeshtastic_DraginoOtaPacket_DownlinkPacket_Finalize_reboot_after_commit_tag 4
#define temeshtastic_DraginoOtaPacket_DownlinkPacket_Abort_session_id_tag 1
#define temeshtastic_DraginoOtaPacket_DownlinkPacket_Abort_image_id_tag 2
#define temeshtastic_DraginoOtaPacket_DownlinkPacket_GetStatus_include_bootloader_status_tag 1
#define temeshtastic_DraginoOtaPacket_DownlinkPacket_Reboot_session_id_tag 1
#define temeshtastic_DraginoOtaPacket_DownlinkPacket_Reboot_image_id_tag 2
#define temeshtastic_DraginoOtaPacket_DownlinkPacket_begin_tag 1
#define temeshtastic_DraginoOtaPacket_DownlinkPacket_chunk_tag 2
#define temeshtastic_DraginoOtaPacket_DownlinkPacket_finalize_tag 3
#define temeshtastic_DraginoOtaPacket_DownlinkPacket_abort_tag 4
#define temeshtastic_DraginoOtaPacket_DownlinkPacket_get_status_tag 5
#define temeshtastic_DraginoOtaPacket_DownlinkPacket_reboot_tag 6
#define temeshtastic_DraginoOtaPacket_UplinkPacket_Ack_session_id_tag 1
#define temeshtastic_DraginoOtaPacket_UplinkPacket_Ack_image_id_tag 2
#define temeshtastic_DraginoOtaPacket_UplinkPacket_Ack_chunk_index_tag 3
#define temeshtastic_DraginoOtaPacket_UplinkPacket_Ack_status_tag 4
#define temeshtastic_DraginoOtaPacket_UplinkPacket_Ack_message_tag 5
#define temeshtastic_DraginoOtaPacket_UplinkPacket_Status_session_id_tag 1
#define temeshtastic_DraginoOtaPacket_UplinkPacket_Status_image_id_tag 2
#define temeshtastic_DraginoOtaPacket_UplinkPacket_Status_state_tag 3
#define temeshtastic_DraginoOtaPacket_UplinkPacket_Status_image_size_tag 4
#define temeshtastic_DraginoOtaPacket_UplinkPacket_Status_written_size_tag 5
#define temeshtastic_DraginoOtaPacket_UplinkPacket_Status_next_offset_tag 6
#define temeshtastic_DraginoOtaPacket_UplinkPacket_Status_last_error_tag 7
#define temeshtastic_DraginoOtaPacket_UplinkPacket_Status_bootloader_status_tag 8
#define temeshtastic_DraginoOtaPacket_UplinkPacket_Status_bootloader_detail_tag 9
#define temeshtastic_DraginoOtaPacket_UplinkPacket_Status_bootloader_sequence_tag 10
#define temeshtastic_DraginoOtaPacket_UplinkPacket_Status_bootloader_image_id_tag 11
#define temeshtastic_DraginoOtaPacket_UplinkPacket_ack_tag 1
#define temeshtastic_DraginoOtaPacket_UplinkPacket_status_tag 2
#define temeshtastic_DraginoOtaPacket_downlink_packet_tag 1
#define temeshtastic_DraginoOtaPacket_uplink_packet_tag 2

/* Struct field encoding specification for nanopb */
#define temeshtastic_DraginoOtaPacket_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (packet_type,downlink_packet,packet_type.downlink_packet),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (packet_type,uplink_packet,packet_type.uplink_packet),   2)
#define temeshtastic_DraginoOtaPacket_CALLBACK NULL
#define temeshtastic_DraginoOtaPacket_DEFAULT NULL
#define temeshtastic_DraginoOtaPacket_packet_type_downlink_packet_MSGTYPE temeshtastic_DraginoOtaPacket_DownlinkPacket
#define temeshtastic_DraginoOtaPacket_packet_type_uplink_packet_MSGTYPE temeshtastic_DraginoOtaPacket_UplinkPacket

#define temeshtastic_DraginoOtaPacket_DownlinkPacket_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,begin,payload.begin),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,chunk,payload.chunk),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,finalize,payload.finalize),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,abort,payload.abort),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,get_status,payload.get_status),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,reboot,payload.reboot),   6)
#define temeshtastic_DraginoOtaPacket_DownlinkPacket_CALLBACK NULL
#define temeshtastic_DraginoOtaPacket_DownlinkPacket_DEFAULT NULL
#define temeshtastic_DraginoOtaPacket_DownlinkPacket_payload_begin_MSGTYPE temeshtastic_DraginoOtaPacket_DownlinkPacket_Begin
#define temeshtastic_DraginoOtaPacket_DownlinkPacket_payload_chunk_MSGTYPE temeshtastic_DraginoOtaPacket_DownlinkPacket_Chunk
#define temeshtastic_DraginoOtaPacket_DownlinkPacket_payload_finalize_MSGTYPE temeshtastic_DraginoOtaPacket_DownlinkPacket_Finalize
#define temeshtastic_DraginoOtaPacket_DownlinkPacket_payload_abort_MSGTYPE temeshtastic_DraginoOtaPacket_DownlinkPacket_Abort
#define temeshtastic_DraginoOtaPacket_DownlinkPacket_payload_get_status_MSGTYPE temeshtastic_DraginoOtaPacket_DownlinkPacket_GetStatus
#define temeshtastic_DraginoOtaPacket_DownlinkPacket_payload_reboot_MSGTYPE temeshtastic_DraginoOtaPacket_DownlinkPacket_Reboot

#define temeshtastic_DraginoOtaPacket_DownlinkPacket_Begin_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   session_id,        1) \
X(a, STATIC,   SINGULAR, UINT32,   image_id,          2) \
X(a, STATIC,   SINGULAR, UINT32,   image_size,        3) \
X(a, STATIC,   SINGULAR, UINT32,   image_crc32,       4) \
X(a, STATIC,   SINGULAR, BYTES,    image_sha256,      5) \
X(a, STATIC,   SINGULAR, UINT32,   chunk_size,        6) \
X(a, STATIC,   SINGULAR, UINT32,   total_chunks,      7) \
X(a, STATIC,   SINGULAR, UINT32,   firmware_version,   8) \
X(a, STATIC,   SINGULAR, UINT32,   build_number,      9) \
X(a, STATIC,   SINGULAR, UINT32,   min_bootloader_version,  10) \
X(a, STATIC,   SINGULAR, STRING,   target_hw_model,  11) \
X(a, STATIC,   SINGULAR, STRING,   target_app_profile,  12) \
X(a, STATIC,   SINGULAR, UINT32,   flags,            13)
#define temeshtastic_DraginoOtaPacket_DownlinkPacket_Begin_CALLBACK NULL
#define temeshtastic_DraginoOtaPacket_DownlinkPacket_Begin_DEFAULT NULL

#define temeshtastic_DraginoOtaPacket_DownlinkPacket_Chunk_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   session_id,        1) \
X(a, STATIC,   SINGULAR, UINT32,   image_id,          2) \
X(a, STATIC,   SINGULAR, UINT32,   chunk_index,       3) \
X(a, STATIC,   SINGULAR, UINT32,   offset,            4) \
X(a, STATIC,   SINGULAR, BYTES,    data,              5) \
X(a, STATIC,   SINGULAR, UINT32,   chunk_crc32,       6)
#define temeshtastic_DraginoOtaPacket_DownlinkPacket_Chunk_CALLBACK NULL
#define temeshtastic_DraginoOtaPacket_DownlinkPacket_Chunk_DEFAULT NULL

#define temeshtastic_DraginoOtaPacket_DownlinkPacket_Finalize_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   session_id,        1) \
X(a, STATIC,   SINGULAR, UINT32,   image_id,          2) \
X(a, STATIC,   SINGULAR, UINT32,   manifest_slot,     3) \
X(a, STATIC,   SINGULAR, BOOL,     reboot_after_commit,   4)
#define temeshtastic_DraginoOtaPacket_DownlinkPacket_Finalize_CALLBACK NULL
#define temeshtastic_DraginoOtaPacket_DownlinkPacket_Finalize_DEFAULT NULL

#define temeshtastic_DraginoOtaPacket_DownlinkPacket_Abort_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   session_id,        1) \
X(a, STATIC,   SINGULAR, UINT32,   image_id,          2)
#define temeshtastic_DraginoOtaPacket_DownlinkPacket_Abort_CALLBACK NULL
#define temeshtastic_DraginoOtaPacket_DownlinkPacket_Abort_DEFAULT NULL

#define temeshtastic_DraginoOtaPacket_DownlinkPacket_GetStatus_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     include_bootloader_status,   1)
#define temeshtastic_DraginoOtaPacket_DownlinkPacket_GetStatus_CALLBACK NULL
#define temeshtastic_DraginoOtaPacket_DownlinkPacket_GetStatus_DEFAULT NULL

#define temeshtastic_DraginoOtaPacket_DownlinkPacket_Reboot_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   session_id,        1) \
X(a, STATIC,   SINGULAR, UINT32,   image_id,          2)
#define temeshtastic_DraginoOtaPacket_DownlinkPacket_Reboot_CALLBACK NULL
#define temeshtastic_DraginoOtaPacket_DownlinkPacket_Reboot_DEFAULT NULL

#define temeshtastic_DraginoOtaPacket_UplinkPacket_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,ack,payload.ack),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,status,payload.status),   2)
#define temeshtastic_DraginoOtaPacket_UplinkPacket_CALLBACK NULL
#define temeshtastic_DraginoOtaPacket_UplinkPacket_DEFAULT NULL
#define temeshtastic_DraginoOtaPacket_UplinkPacket_payload_ack_MSGTYPE temeshtastic_DraginoOtaPacket_UplinkPacket_Ack
#define temeshtastic_DraginoOtaPacket_UplinkPacket_payload_status_MSGTYPE temeshtastic_DraginoOtaPacket_UplinkPacket_Status

#define temeshtastic_DraginoOtaPacket_UplinkPacket_Ack_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   session_id,        1) \
X(a, STATIC,   SINGULAR, UINT32,   image_id,          2) \
X(a, STATIC,   SINGULAR, UINT32,   chunk_index,       3) \
X(a, STATIC,   SINGULAR, UENUM,    status,            4) \
X(a, STATIC,   SINGULAR, STRING,   message,           5)
#define temeshtastic_DraginoOtaPacket_UplinkPacket_Ack_CALLBACK NULL
#define temeshtastic_DraginoOtaPacket_UplinkPacket_Ack_DEFAULT NULL

#define temeshtastic_DraginoOtaPacket_UplinkPacket_Status_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   session_id,        1) \
X(a, STATIC,   SINGULAR, UINT32,   image_id,          2) \
X(a, STATIC,   SINGULAR, UENUM,    state,             3) \
X(a, STATIC,   SINGULAR, UINT32,   image_size,        4) \
X(a, STATIC,   SINGULAR, UINT32,   written_size,      5) \
X(a, STATIC,   SINGULAR, UINT32,   next_offset,       6) \
X(a, STATIC,   SINGULAR, UINT32,   last_error,        7) \
X(a, STATIC,   SINGULAR, UINT32,   bootloader_status,   8) \
X(a, STATIC,   SINGULAR, UINT32,   bootloader_detail,   9) \
X(a, STATIC,   SINGULAR, UINT32,   bootloader_sequence,  10) \
X(a, STATIC,   SINGULAR, UINT32,   bootloader_image_id,  11)
#define temeshtastic_DraginoOtaPacket_UplinkPacket_Status_CALLBACK NULL
#define temeshtastic_DraginoOtaPacket_UplinkPacket_Status_DEFAULT NULL

extern const pb_msgdesc_t temeshtastic_DraginoOtaPacket_msg;
extern const pb_msgdesc_t temeshtastic_DraginoOtaPacket_DownlinkPacket_msg;
extern const pb_msgdesc_t temeshtastic_DraginoOtaPacket_DownlinkPacket_Begin_msg;
extern const pb_msgdesc_t temeshtastic_DraginoOtaPacket_DownlinkPacket_Chunk_msg;
extern const pb_msgdesc_t temeshtastic_DraginoOtaPacket_DownlinkPacket_Finalize_msg;
extern const pb_msgdesc_t temeshtastic_DraginoOtaPacket_DownlinkPacket_Abort_msg;
extern const pb_msgdesc_t temeshtastic_DraginoOtaPacket_DownlinkPacket_GetStatus_msg;
extern const pb_msgdesc_t temeshtastic_DraginoOtaPacket_DownlinkPacket_Reboot_msg;
extern const pb_msgdesc_t temeshtastic_DraginoOtaPacket_UplinkPacket_msg;
extern const pb_msgdesc_t temeshtastic_DraginoOtaPacket_UplinkPacket_Ack_msg;
extern const pb_msgdesc_t temeshtastic_DraginoOtaPacket_UplinkPacket_Status_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define temeshtastic_DraginoOtaPacket_fields &temeshtastic_DraginoOtaPacket_msg
#define temeshtastic_DraginoOtaPacket_DownlinkPacket_fields &temeshtastic_DraginoOtaPacket_DownlinkPacket_msg
#define temeshtastic_DraginoOtaPacket_DownlinkPacket_Begin_fields &temeshtastic_DraginoOtaPacket_DownlinkPacket_Begin_msg
#define temeshtastic_DraginoOtaPacket_DownlinkPacket_Chunk_fields &temeshtastic_DraginoOtaPacket_DownlinkPacket_Chunk_msg
#define temeshtastic_DraginoOtaPacket_DownlinkPacket_Finalize_fields &temeshtastic_DraginoOtaPacket_DownlinkPacket_Finalize_msg
#define temeshtastic_DraginoOtaPacket_DownlinkPacket_Abort_fields &temeshtastic_DraginoOtaPacket_DownlinkPacket_Abort_msg
#define temeshtastic_DraginoOtaPacket_DownlinkPacket_GetStatus_fields &temeshtastic_DraginoOtaPacket_DownlinkPacket_GetStatus_msg
#define temeshtastic_DraginoOtaPacket_DownlinkPacket_Reboot_fields &temeshtastic_DraginoOtaPacket_DownlinkPacket_Reboot_msg
#define temeshtastic_DraginoOtaPacket_UplinkPacket_fields &temeshtastic_DraginoOtaPacket_UplinkPacket_msg
#define temeshtastic_DraginoOtaPacket_UplinkPacket_Ack_fields &temeshtastic_DraginoOtaPacket_UplinkPacket_Ack_msg
#define temeshtastic_DraginoOtaPacket_UplinkPacket_Status_fields &temeshtastic_DraginoOtaPacket_UplinkPacket_Status_msg

/* Maximum encoded size of messages (where known) */
#define TEMESHTASTIC_PROTOBUF_DRAGINOOTA_PB_H_MAX_SIZE temeshtastic_DraginoOtaPacket_size
#define temeshtastic_DraginoOtaPacket_DownlinkPacket_Abort_size 12
#define temeshtastic_DraginoOtaPacket_DownlinkPacket_Begin_size 144
#define temeshtastic_DraginoOtaPacket_DownlinkPacket_Chunk_size 225
#define temeshtastic_DraginoOtaPacket_DownlinkPacket_Finalize_size 20
#define temeshtastic_DraginoOtaPacket_DownlinkPacket_GetStatus_size 2
#define temeshtastic_DraginoOtaPacket_DownlinkPacket_Reboot_size 12
#define temeshtastic_DraginoOtaPacket_DownlinkPacket_size 228
#define temeshtastic_DraginoOtaPacket_UplinkPacket_Ack_size 69
#define temeshtastic_DraginoOtaPacket_UplinkPacket_Status_size 62
#define temeshtastic_DraginoOtaPacket_UplinkPacket_size 71
#define temeshtastic_DraginoOtaPacket_size       231

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
