/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9 */

#ifndef PB_TEMESHTASTIC_PROTOBUF_PRIVATECONFIG_PB_H_INCLUDED
#define PB_TEMESHTASTIC_PROTOBUF_PRIVATECONFIG_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* The status of the factory identity, which can indicate whether the identity is valid, empty, or has errors. */
typedef enum _temeshtastic_DeviceFactoryIdentity_FactoryIdentityStatus {
    temeshtastic_DeviceFactoryIdentity_FactoryIdentityStatus_FACTORY_IDENTITY_EMPTY = 0,
    temeshtastic_DeviceFactoryIdentity_FactoryIdentityStatus_FACTORY_IDENTITY_VALID = 1,
    temeshtastic_DeviceFactoryIdentity_FactoryIdentityStatus_FACTORY_IDENTITY_CRC_ERROR = 2,
    temeshtastic_DeviceFactoryIdentity_FactoryIdentityStatus_FACTORY_IDENTITY_INVALID_FORMAT = 3,
    temeshtastic_DeviceFactoryIdentity_FactoryIdentityStatus_FACTORY_IDENTITY_LOCKED = 4
} temeshtastic_DeviceFactoryIdentity_FactoryIdentityStatus;

/* Wake-up strategy */
typedef enum _temeshtastic_SyncWakeupConfig_WakeupStrategy {
    temeshtastic_SyncWakeupConfig_WakeupStrategy_STRATEGY_FIXED = 0, /* Fixed interval */
    temeshtastic_SyncWakeupConfig_WakeupStrategy_STRATEGY_SCHEDULED = 1 /* Scheduled */
} temeshtastic_SyncWakeupConfig_WakeupStrategy;

/* The reset type enumeration (defined inside PrivateConfigPacket) */
typedef enum _temeshtastic_PrivateConfigPacket_SetNetWorkConfig_ResetType {
    /* No reset */
    temeshtastic_PrivateConfigPacket_SetNetWorkConfig_ResetType_RESET_TYPE_NONE = 0,
    /* Factory reset - clear all configurations */
    temeshtastic_PrivateConfigPacket_SetNetWorkConfig_ResetType_RESET_TYPE_FACTORY = 1, /* 恢复出厂设置 */
    /* Network reset - clear network-related configurations */
    temeshtastic_PrivateConfigPacket_SetNetWorkConfig_ResetType_RESET_TYPE_NETWORK = 2 /* 重置网络配置 */
} temeshtastic_PrivateConfigPacket_SetNetWorkConfig_ResetType;

typedef enum _temeshtastic_PrivateConfigPacket_SetInfoLabelConfig_SetInfoLabel_InfoLabelAction {
    /* Add a new info label */
    temeshtastic_PrivateConfigPacket_SetInfoLabelConfig_SetInfoLabel_InfoLabelAction_ADD = 0,
    /* Update an existing info label */
    temeshtastic_PrivateConfigPacket_SetInfoLabelConfig_SetInfoLabel_InfoLabelAction_UPDATE = 1,
    /* Delete an info label */
    temeshtastic_PrivateConfigPacket_SetInfoLabelConfig_SetInfoLabel_InfoLabelAction_DELETE = 2
} temeshtastic_PrivateConfigPacket_SetInfoLabelConfig_SetInfoLabel_InfoLabelAction;

typedef enum _temeshtastic_PrivateConfigPacket_EnterBootloader_BootloaderReason {
    temeshtastic_PrivateConfigPacket_EnterBootloader_BootloaderReason_BOOTLOADER_REASON_UNKNOWN = 0,
    temeshtastic_PrivateConfigPacket_EnterBootloader_BootloaderReason_BOOTLOADER_REASON_SERIAL = 1,
    temeshtastic_PrivateConfigPacket_EnterBootloader_BootloaderReason_BOOTLOADER_REASON_BLUETOOTH = 2,
    temeshtastic_PrivateConfigPacket_EnterBootloader_BootloaderReason_BOOTLOADER_REASON_UPPER_COMPUTER = 3,
    temeshtastic_PrivateConfigPacket_EnterBootloader_BootloaderReason_BOOTLOADER_REASON_TEST = 4
} temeshtastic_PrivateConfigPacket_EnterBootloader_BootloaderReason;

typedef enum _temeshtastic_PrivateConfigPacket_OperationResult_Operation {
    temeshtastic_PrivateConfigPacket_OperationResult_Operation_OPERATION_UNKNOWN = 0,
    temeshtastic_PrivateConfigPacket_OperationResult_Operation_OPERATION_SET_FACTORY_IDENTITY = 1,
    temeshtastic_PrivateConfigPacket_OperationResult_Operation_OPERATION_GET_FACTORY_IDENTITY = 2,
    temeshtastic_PrivateConfigPacket_OperationResult_Operation_OPERATION_CHANNEL12_CONFIG = 3,
    temeshtastic_PrivateConfigPacket_OperationResult_Operation_OPERATION_JOIN_NETWORK_V2 = 4,
    temeshtastic_PrivateConfigPacket_OperationResult_Operation_OPERATION_CHANGE_ADMIN = 5,
    temeshtastic_PrivateConfigPacket_OperationResult_Operation_OPERATION_RESET_NETWORK_CONFIG = 6,
    temeshtastic_PrivateConfigPacket_OperationResult_Operation_OPERATION_CHANGE_NETWORK_KEY = 7,
    temeshtastic_PrivateConfigPacket_OperationResult_Operation_OPERATION_TRUSTED_GATEWAY_CONFIG = 8,
    temeshtastic_PrivateConfigPacket_OperationResult_Operation_OPERATION_SYNC_WAKEUP_CONFIG = 9,
    temeshtastic_PrivateConfigPacket_OperationResult_Operation_OPERATION_INFO_LABEL_CONFIG = 10,
    temeshtastic_PrivateConfigPacket_OperationResult_Operation_OPERATION_ENTER_BOOTLOADER = 11
} temeshtastic_PrivateConfigPacket_OperationResult_Operation;

typedef enum _temeshtastic_PrivateConfigPacket_OperationResult_Status {
    temeshtastic_PrivateConfigPacket_OperationResult_Status_STATUS_UNKNOWN = 0,
    temeshtastic_PrivateConfigPacket_OperationResult_Status_STATUS_OK = 1,
    temeshtastic_PrivateConfigPacket_OperationResult_Status_STATUS_NO_CHANGE = 2,
    temeshtastic_PrivateConfigPacket_OperationResult_Status_STATUS_PENDING_CHANNEL12 = 3,
    temeshtastic_PrivateConfigPacket_OperationResult_Status_STATUS_ALREADY_ENROLLED = 4,
    temeshtastic_PrivateConfigPacket_OperationResult_Status_STATUS_NOT_ENROLLED = 5,
    temeshtastic_PrivateConfigPacket_OperationResult_Status_STATUS_NOT_AUTHORIZED = 6,
    temeshtastic_PrivateConfigPacket_OperationResult_Status_STATUS_BAD_AUTH_CODE = 7,
    temeshtastic_PrivateConfigPacket_OperationResult_Status_STATUS_STALE_NONCE = 8,
    temeshtastic_PrivateConfigPacket_OperationResult_Status_STATUS_INVALID_STATE = 9,
    temeshtastic_PrivateConfigPacket_OperationResult_Status_STATUS_INVALID_SIZE = 10,
    temeshtastic_PrivateConfigPacket_OperationResult_Status_STATUS_INVALID_ARGUMENT = 11,
    temeshtastic_PrivateConfigPacket_OperationResult_Status_STATUS_SAVE_FAILED = 12,
    temeshtastic_PrivateConfigPacket_OperationResult_Status_STATUS_UNSUPPORTED = 13
} temeshtastic_PrivateConfigPacket_OperationResult_Status;

/* Struct definitions */
typedef PB_BYTES_ARRAY_T(16) temeshtastic_JoinLockAdvertise_join_challenge_t;
/*  */
typedef struct _temeshtastic_JoinLockAdvertise {
    temeshtastic_JoinLockAdvertise_join_challenge_t join_challenge;
    uint32_t dev_eui_hi;
    uint32_t dev_eui_lo;
    char sn[20];
} temeshtastic_JoinLockAdvertise;

typedef PB_BYTES_ARRAY_T(32) temeshtastic_DeviceFactoryIdentity_device_private_key_t;
typedef PB_BYTES_ARRAY_T(16) temeshtastic_DeviceFactoryIdentity_legacy_app_key_t;
/* NO.1 - The device information stored in the secure element, which is read-only and cannot be modified after manufacturing. This information is used for device identification, authentication, and other security-related functions. */
typedef struct _temeshtastic_DeviceFactoryIdentity {
    /* The factory configuration version */
    uint32_t factory_version;
    /* The device SN (Serial Number) */
    char sn[20];
    /* The device Dev EUI */
    uint32_t dev_eui_hi;
    uint32_t dev_eui_lo;
    /* Meshtastic native Curve25519 private key.
 固件用它派生 config.security.public_key / owner.public_key。 */
    temeshtastic_DeviceFactoryIdentity_device_private_key_t device_private_key;
    /* The manufacturing timestamp (Unix epoch time) */
    uint64_t manufacturing_timestamp;
    /* The status of the factory identity, which can indicate whether the identity is valid, empty, or has errors. */
    temeshtastic_DeviceFactoryIdentity_FactoryIdentityStatus status;
    /* The CRC32 checksum of the factory identity data for integrity verification */
    uint32_t identity_crc;
    temeshtastic_DeviceFactoryIdentity_legacy_app_key_t legacy_app_key;
} temeshtastic_DeviceFactoryIdentity;

typedef PB_BYTES_ARRAY_T(32) temeshtastic_NetWorkConfig_network_public_key_t;
typedef PB_BYTES_ARRAY_T(32) temeshtastic_NetWorkConfig_network_seed_t;
/* NO.2 - NetWorkConfig is the network configuration stored in the secure element, which can be read by the device and used for network authentication and other network-related functions. This configuration includes the network public key, trusted time sources, and other parameters that can be updated after manufacturing. */
typedef struct _temeshtastic_NetWorkConfig {
    /* The network public key (32 bytes) */
    temeshtastic_NetWorkConfig_network_public_key_t network_public_key;
    /* The timestamp of the last admin change operation */
    uint64_t last_change_timestamp;
    /* Whether the gateway is single */
    bool is_single_gateway;
    /* The list of trusted gateways */
    pb_size_t trusted_gateway_sources_count;
    uint32_t trusted_gateway_sources[4];
    temeshtastic_NetWorkConfig_network_seed_t network_seed;
} temeshtastic_NetWorkConfig;

/* Time slot configuration */
typedef struct _temeshtastic_SyncWakeupConfig_TimeSlot {
    /* The start hour of the time slot (0-23) */
    uint32_t start_hour; /* Start hour (0-23) */
    /* The end hour of the time slot (0-23) */
    uint32_t end_hour; /* End hour (0-23) */
    /* The wake-up interval for this time slot in minutes */
    uint32_t interval_min; /* Wake-up interval for this time slot (minutes) */
    /* The alignment minute for this time slot (0-59) */
    uint32_t align_minute; /* Alignment minute for this time slot (0-59) */
} temeshtastic_SyncWakeupConfig_TimeSlot;

typedef struct _temeshtastic_SyncWakeupConfig_FixedWakeup {
    /* Strategy 1: Fixed Interval
 The wake-up interval in minutes */
    uint32_t interval_min;
    /* The alignment minute for wake-up (0-59), only applicable for fixed strategy */
    uint32_t align_minute;
    /* The time offset in seconds for scheduled wake-up, only applicable for scheduled strategy */
    uint32_t offset_sec;
} temeshtastic_SyncWakeupConfig_FixedWakeup;

typedef struct _temeshtastic_SyncWakeupConfig_ScheduledWakeup {
    /* Strategy 2: Scheduled
 The time offset in seconds for scheduled wake-up */
    uint32_t offset_sec;
    /* The list of time slots for scheduled wake-up */
    pb_size_t time_slots_count;
    temeshtastic_SyncWakeupConfig_TimeSlot time_slots[4];
} temeshtastic_SyncWakeupConfig_ScheduledWakeup;

/* 新增：唤醒后的通信窗口配置 */
typedef struct _temeshtastic_SyncWakeupConfig_WakeupWindow {
    uint32_t startup_delay_sec; /* 唤醒后等待系统初始化多久再发送 */
    uint32_t random_delay_max_sec; /* 业务上报前随机错峰最大秒数 */
    uint32_t gateway_wait_sec; /* 发完上报后等待网关下发命令多久 */
    uint32_t final_wait_sec; /* 关蓝牙/收尾后再等多久睡眠 */
    uint32_t degraded_window_sec; /* RTC质量不足时保持活跃多久 */
    uint32_t factory_window_sec; /* 未入网/出厂模式保持活跃多久 */
} temeshtastic_SyncWakeupConfig_WakeupWindow;

/* NO.3 - The private configuration stored in the secure element, which can be read and modified by the administrator. This configuration includes device settings, company information, and other parameters that can be updated after manufacturing. */
typedef struct _temeshtastic_SyncWakeupConfig {
    /* Whether to enable sync wake-up */
    bool enabled;
    /* The wake-up strategy to use */
    temeshtastic_SyncWakeupConfig_WakeupStrategy strategy;
    /* The fixed wake-up configuration */
    bool has_fixed_wakeup;
    temeshtastic_SyncWakeupConfig_FixedWakeup fixed_wakeup;
    /* The scheduled wake-up configuration */
    bool has_scheduled_wakeup;
    temeshtastic_SyncWakeupConfig_ScheduledWakeup scheduled_wakeup;
    /* The wake-up window configuration */
    bool has_wakeup_window;
    temeshtastic_SyncWakeupConfig_WakeupWindow wakeup_window;
} temeshtastic_SyncWakeupConfig;

typedef struct _temeshtastic_DeviceLabels_InfoLabel {
    /* The unique identifier for this info label */
    uint32_t id;
    /* The key name of the info label */
    char key[20];
    /* The value of the info label */
    char value[20];
} temeshtastic_DeviceLabels_InfoLabel;

/* NO.4 - The device labels stored in the secure element, which can be read and modified by the administrator. These labels include key-value pairs of information about the device, such as location, owner, or other custom attributes that can be used for device management and organization. */
typedef struct _temeshtastic_DeviceLabels {
    /* The list of info labels */
    pb_size_t info_labels_count;
    temeshtastic_DeviceLabels_InfoLabel info_labels[10]; /* repeated FunctionLabel function_labels = 2 [(nanopb).max_count = 10]; */
} temeshtastic_DeviceLabels;

typedef struct _temeshtastic_PrivateConfig {
    /* NO.1 */
    bool has_factory_identity;
    temeshtastic_DeviceFactoryIdentity factory_identity;
    /* NO.2 */
    bool has_network_config;
    temeshtastic_NetWorkConfig network_config;
    /* NO.3 */
    bool has_sync_wakeup;
    temeshtastic_SyncWakeupConfig sync_wakeup;
    /* NO.4 */
    bool has_device_labels;
    temeshtastic_DeviceLabels device_labels;
    /* The version of the private configuration */
    uint32_t private_version;
} temeshtastic_PrivateConfig;

/* FactoryIdentity */
typedef struct _temeshtastic_PrivateConfigPacket_SetDeviceFactoryIdentity {
    pb_size_t which_payload;
    union {
        /* Whether to reset the factory identity to the default values */
        bool get_factory_identity;
        /* The device factory identity to set */
        temeshtastic_DeviceFactoryIdentity factory_identity;
    } payload;
} temeshtastic_PrivateConfigPacket_SetDeviceFactoryIdentity;

typedef PB_BYTES_ARRAY_T(32) temeshtastic_PrivateConfigPacket_SetNetWorkConfig_Channel12Config_psk1_t;
typedef PB_BYTES_ARRAY_T(32) temeshtastic_PrivateConfigPacket_SetNetWorkConfig_Channel12Config_psk2_t;
/* The channel configuration for 2 channels */
typedef struct _temeshtastic_PrivateConfigPacket_SetNetWorkConfig_Channel12Config {
    /* Channel1 name */
    char channel1_name[20];
    /* PSK for channel 1 (32 bytes) */
    temeshtastic_PrivateConfigPacket_SetNetWorkConfig_Channel12Config_psk1_t psk1;
    /* Channel2 name */
    char channel2_name[20];
    /* PSK for channel 2 (32 bytes) */
    temeshtastic_PrivateConfigPacket_SetNetWorkConfig_Channel12Config_psk2_t psk2;
} temeshtastic_PrivateConfigPacket_SetNetWorkConfig_Channel12Config;

typedef PB_BYTES_ARRAY_T(32) temeshtastic_PrivateConfigPacket_SetNetWorkConfig_ChangeNetworkKey_new_network_public_key_t;
typedef PB_BYTES_ARRAY_T(32) temeshtastic_PrivateConfigPacket_SetNetWorkConfig_ChangeNetworkKey_auth_code_t;
typedef PB_BYTES_ARRAY_T(32) temeshtastic_PrivateConfigPacket_SetNetWorkConfig_ChangeNetworkKey_new_network_seed_t;
/* The request to change the network key. */
typedef struct _temeshtastic_PrivateConfigPacket_SetNetWorkConfig_ChangeNetworkKey {
    /* The new network public key (32 bytes) */
    temeshtastic_PrivateConfigPacket_SetNetWorkConfig_ChangeNetworkKey_new_network_public_key_t new_network_public_key; /* 新网络公钥 (32字节) */
    /* The timestamp for replay protection */
    uint64_t timestamp;
    /* HMAC-SHA256(admin_auth_key, command_data), 32 bytes. */
    temeshtastic_PrivateConfigPacket_SetNetWorkConfig_ChangeNetworkKey_auth_code_t auth_code;
    temeshtastic_PrivateConfigPacket_SetNetWorkConfig_ChangeNetworkKey_new_network_seed_t new_network_seed;
} temeshtastic_PrivateConfigPacket_SetNetWorkConfig_ChangeNetworkKey;

typedef PB_BYTES_ARRAY_T(32) temeshtastic_PrivateConfigPacket_SetNetWorkConfig_ChangeAdmin_new_gateway_public_key_t;
typedef PB_BYTES_ARRAY_T(32) temeshtastic_PrivateConfigPacket_SetNetWorkConfig_ChangeAdmin_auth_code_t;
/* The network configuration to set */
typedef struct _temeshtastic_PrivateConfigPacket_SetNetWorkConfig_ChangeAdmin {
    /* The new gateway public key (32 bytes) */
    temeshtastic_PrivateConfigPacket_SetNetWorkConfig_ChangeAdmin_new_gateway_public_key_t new_gateway_public_key; /* 新网关公钥 (32字节) */
    /* The new gateway node ID */
    uint32_t new_gateway_node_id; /* 新网关节点ID */
    /* The timestamp for replay protection */
    uint64_t timestamp; /* 时间戳（防重放） */
    temeshtastic_PrivateConfigPacket_SetNetWorkConfig_ChangeAdmin_auth_code_t auth_code;
} temeshtastic_PrivateConfigPacket_SetNetWorkConfig_ChangeAdmin;

typedef PB_BYTES_ARRAY_T(32) temeshtastic_PrivateConfigPacket_SetNetWorkConfig_ResetNetworkConfig_auth_code_t;
/* The request to reset the network configuration */
typedef struct _temeshtastic_PrivateConfigPacket_SetNetWorkConfig_ResetNetworkConfig {
    /* The type of reset to perform */
    temeshtastic_PrivateConfigPacket_SetNetWorkConfig_ResetType reset_type;
    /* The timestamp for replay protection */
    uint64_t timestamp;
    temeshtastic_PrivateConfigPacket_SetNetWorkConfig_ResetNetworkConfig_auth_code_t auth_code;
} temeshtastic_PrivateConfigPacket_SetNetWorkConfig_ResetNetworkConfig;

/* The list of trusted gateway sources */
typedef struct _temeshtastic_PrivateConfigPacket_SetNetWorkConfig_TrustedGatewayConfig {
    bool is_single_gateway; /* Whether the gateway is non-single */
    pb_size_t which_payload;
    union {
        bool get_trusted_gateway_list;
        uint32_t add_trusted_gateway;
        uint32_t remove_trusted_gateway;
    } payload;
} temeshtastic_PrivateConfigPacket_SetNetWorkConfig_TrustedGatewayConfig;

typedef PB_BYTES_ARRAY_T(32) temeshtastic_PrivateConfigPacket_SetNetWorkConfig_JoinNetWorkV2_network_public_key_t;
typedef PB_BYTES_ARRAY_T(32) temeshtastic_PrivateConfigPacket_SetNetWorkConfig_JoinNetWorkV2_network_seed_t;
typedef PB_BYTES_ARRAY_T(32) temeshtastic_PrivateConfigPacket_SetNetWorkConfig_JoinNetWorkV2_auth_code_t;
/* Quick network access */
typedef struct _temeshtastic_PrivateConfigPacket_SetNetWorkConfig_JoinNetWorkV2 {
    /* network公钥 (32字节) */
    temeshtastic_PrivateConfigPacket_SetNetWorkConfig_JoinNetWorkV2_network_public_key_t network_public_key;
    /* Network seed used to derive Channel 1/2 PSK. */
    temeshtastic_PrivateConfigPacket_SetNetWorkConfig_JoinNetWorkV2_network_seed_t network_seed;
    /* The timestamp for replay protection */
    uint64_t timestamp;
    /* HMAC-SHA256(device_private_key, join_data), 32 bytes. */
    temeshtastic_PrivateConfigPacket_SetNetWorkConfig_JoinNetWorkV2_auth_code_t auth_code;
} temeshtastic_PrivateConfigPacket_SetNetWorkConfig_JoinNetWorkV2;

typedef PB_BYTES_ARRAY_T(32) temeshtastic_PrivateConfigPacket_SetNetWorkConfig_GatewayAnnounce_network_public_key_t;
typedef PB_BYTES_ARRAY_T(32) temeshtastic_PrivateConfigPacket_SetNetWorkConfig_GatewayAnnounce_auth_code_t;
typedef struct _temeshtastic_PrivateConfigPacket_SetNetWorkConfig_GatewayAnnounce {
    temeshtastic_PrivateConfigPacket_SetNetWorkConfig_GatewayAnnounce_network_public_key_t network_public_key;
    temeshtastic_PrivateConfigPacket_SetNetWorkConfig_GatewayAnnounce_auth_code_t auth_code;
} temeshtastic_PrivateConfigPacket_SetNetWorkConfig_GatewayAnnounce;

/* Network Configuration */
typedef struct _temeshtastic_PrivateConfigPacket_SetNetWorkConfig {
    pb_size_t which_payload;
    union {
        bool get_network_config;
        temeshtastic_PrivateConfigPacket_SetNetWorkConfig_Channel12Config channel12_config;
        temeshtastic_PrivateConfigPacket_SetNetWorkConfig_ChangeNetworkKey change_network_key;
        temeshtastic_PrivateConfigPacket_SetNetWorkConfig_ChangeAdmin change_admin;
        temeshtastic_PrivateConfigPacket_SetNetWorkConfig_ResetNetworkConfig reset_network_config;
        temeshtastic_PrivateConfigPacket_SetNetWorkConfig_TrustedGatewayConfig trusted_gateway_config;
        temeshtastic_PrivateConfigPacket_SetNetWorkConfig_JoinNetWorkV2 join_network_v2;
        bool get_join_lock_advertise;
        temeshtastic_PrivateConfigPacket_SetNetWorkConfig_GatewayAnnounce gateway_announce;
    } payload;
} temeshtastic_PrivateConfigPacket_SetNetWorkConfig;

typedef struct _temeshtastic_PrivateConfigPacket_SetSyncWakeupConfig_KeepAwakeRequest {
    uint32_t duration_sec; /* 例如 300，0 表示取消长唤醒 */
} temeshtastic_PrivateConfigPacket_SetSyncWakeupConfig_KeepAwakeRequest;

typedef struct _temeshtastic_PrivateConfigPacket_SetSyncWakeupConfig {
    pb_size_t which_payload;
    union {
        /* Whether to get the current sync wake-up configuration */
        bool get_sync_wakeup_config;
        /* The sync wake-up configuration to set */
        temeshtastic_SyncWakeupConfig config;
        temeshtastic_PrivateConfigPacket_SetSyncWakeupConfig_KeepAwakeRequest keep_awake;
    } payload;
} temeshtastic_PrivateConfigPacket_SetSyncWakeupConfig;

typedef struct _temeshtastic_PrivateConfigPacket_SetInfoLabelConfig_SetInfoLabel_InfoLabel {
    /* The unique identifier for this info label */
    uint32_t id;
    /* The key name of the info label */
    char key[20];
    /* The value of the info label */
    char value[20];
} temeshtastic_PrivateConfigPacket_SetInfoLabelConfig_SetInfoLabel_InfoLabel;

typedef struct _temeshtastic_PrivateConfigPacket_SetInfoLabelConfig_SetInfoLabel {
    /* The action to perform on the info label */
    temeshtastic_PrivateConfigPacket_SetInfoLabelConfig_SetInfoLabel_InfoLabelAction action;
    /* The info label to add, update, or delete */
    bool has_info_label;
    temeshtastic_PrivateConfigPacket_SetInfoLabelConfig_SetInfoLabel_InfoLabel info_label;
} temeshtastic_PrivateConfigPacket_SetInfoLabelConfig_SetInfoLabel;

typedef struct _temeshtastic_PrivateConfigPacket_SetInfoLabelConfig {
    pb_size_t which_payload;
    union {
        bool get_info_label_config;
        temeshtastic_PrivateConfigPacket_SetInfoLabelConfig_SetInfoLabel set_info_label;
    } payload;
} temeshtastic_PrivateConfigPacket_SetInfoLabelConfig;

typedef PB_BYTES_ARRAY_T(32) temeshtastic_PrivateConfigPacket_EnterBootloader_auth_code_t;
typedef struct _temeshtastic_PrivateConfigPacket_EnterBootloader {
    temeshtastic_PrivateConfigPacket_EnterBootloader_BootloaderReason reason;
    uint32_t delay_ms;
    temeshtastic_PrivateConfigPacket_EnterBootloader_auth_code_t auth_code;
} temeshtastic_PrivateConfigPacket_EnterBootloader;

/* The downlink packet to send to the device, which can contain commands or configuration updates that the device needs to apply.
 This packet can be used for various purposes, such as updating the device settings, sending control commands,
 or performing other operations that require communication from the server to the device. */
typedef struct _temeshtastic_PrivateConfigPacket_DownlinkPacket {
    pb_size_t which_payload;
    union {
        temeshtastic_PrivateConfigPacket_SetDeviceFactoryIdentity set_factory_identity;
        temeshtastic_PrivateConfigPacket_SetNetWorkConfig set_network_config;
        temeshtastic_PrivateConfigPacket_SetSyncWakeupConfig set_sync_wakeup_config;
        temeshtastic_PrivateConfigPacket_SetInfoLabelConfig set_info_label_config;
        temeshtastic_PrivateConfigPacket_EnterBootloader enter_bootloader;
    } payload;
} temeshtastic_PrivateConfigPacket_DownlinkPacket;

typedef struct _temeshtastic_PrivateConfigPacket_OperationResult {
    temeshtastic_PrivateConfigPacket_OperationResult_Operation operation;
    temeshtastic_PrivateConfigPacket_OperationResult_Status status;
    /* 原始请求包 ID，用于 Debug/网关侧把响应和下发包对应起来 */
    uint32_t request_id;
    /* 处理这个请求的节点 ID */
    uint32_t target_node_id;
    /* 发起配置请求的节点 ID；本地串口/手机方向可为 0 */
    uint32_t source_node_id;
    /* 可选：相关网关节点 ID，例如入网成功后保存的网关 */
    uint32_t gateway_node_id;
    /* 可选：操作时间戳。Join/Change 类可以填请求里的 timestamp */
    uint64_t operation_timestamp;
    /* 可选：给 Debug 工具看的简短原因 */
    char message[48];
} temeshtastic_PrivateConfigPacket_OperationResult;

/* The uplink packet sent from the device to the server, which can contain status reports, sensor data, or other information that the device needs to communicate back to the server. */
typedef struct _temeshtastic_PrivateConfigPacket_UplinkPacket {
    pb_size_t which_payload;
    union {
        /* The device factory identity */
        temeshtastic_DeviceFactoryIdentity factory_identity;
        /* The network configuration */
        temeshtastic_NetWorkConfig network_config;
        /* The sync wake-up configuration */
        temeshtastic_SyncWakeupConfig sync_wakeup_config;
        /* The device labels */
        temeshtastic_DeviceLabels device_labels;
        /* The join lock advertise message */
        temeshtastic_JoinLockAdvertise join_lock_advertise;
        temeshtastic_PrivateConfigPacket_OperationResult operation_result;
    } payload;
} temeshtastic_PrivateConfigPacket_UplinkPacket;

typedef struct _temeshtastic_PrivateConfigPacket {
    pb_size_t which_packet_type;
    union {
        /* The downlink packet to send to the device */
        temeshtastic_PrivateConfigPacket_DownlinkPacket downlink_packet;
        /* The uplink packet sent from the device to the server */
        temeshtastic_PrivateConfigPacket_UplinkPacket uplink_packet;
    } packet_type;
    uint32_t label_id;
} temeshtastic_PrivateConfigPacket;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _temeshtastic_DeviceFactoryIdentity_FactoryIdentityStatus_MIN temeshtastic_DeviceFactoryIdentity_FactoryIdentityStatus_FACTORY_IDENTITY_EMPTY
#define _temeshtastic_DeviceFactoryIdentity_FactoryIdentityStatus_MAX temeshtastic_DeviceFactoryIdentity_FactoryIdentityStatus_FACTORY_IDENTITY_LOCKED
#define _temeshtastic_DeviceFactoryIdentity_FactoryIdentityStatus_ARRAYSIZE ((temeshtastic_DeviceFactoryIdentity_FactoryIdentityStatus)(temeshtastic_DeviceFactoryIdentity_FactoryIdentityStatus_FACTORY_IDENTITY_LOCKED+1))

#define _temeshtastic_SyncWakeupConfig_WakeupStrategy_MIN temeshtastic_SyncWakeupConfig_WakeupStrategy_STRATEGY_FIXED
#define _temeshtastic_SyncWakeupConfig_WakeupStrategy_MAX temeshtastic_SyncWakeupConfig_WakeupStrategy_STRATEGY_SCHEDULED
#define _temeshtastic_SyncWakeupConfig_WakeupStrategy_ARRAYSIZE ((temeshtastic_SyncWakeupConfig_WakeupStrategy)(temeshtastic_SyncWakeupConfig_WakeupStrategy_STRATEGY_SCHEDULED+1))

#define _temeshtastic_PrivateConfigPacket_SetNetWorkConfig_ResetType_MIN temeshtastic_PrivateConfigPacket_SetNetWorkConfig_ResetType_RESET_TYPE_NONE
#define _temeshtastic_PrivateConfigPacket_SetNetWorkConfig_ResetType_MAX temeshtastic_PrivateConfigPacket_SetNetWorkConfig_ResetType_RESET_TYPE_NETWORK
#define _temeshtastic_PrivateConfigPacket_SetNetWorkConfig_ResetType_ARRAYSIZE ((temeshtastic_PrivateConfigPacket_SetNetWorkConfig_ResetType)(temeshtastic_PrivateConfigPacket_SetNetWorkConfig_ResetType_RESET_TYPE_NETWORK+1))

#define _temeshtastic_PrivateConfigPacket_SetInfoLabelConfig_SetInfoLabel_InfoLabelAction_MIN temeshtastic_PrivateConfigPacket_SetInfoLabelConfig_SetInfoLabel_InfoLabelAction_ADD
#define _temeshtastic_PrivateConfigPacket_SetInfoLabelConfig_SetInfoLabel_InfoLabelAction_MAX temeshtastic_PrivateConfigPacket_SetInfoLabelConfig_SetInfoLabel_InfoLabelAction_DELETE
#define _temeshtastic_PrivateConfigPacket_SetInfoLabelConfig_SetInfoLabel_InfoLabelAction_ARRAYSIZE ((temeshtastic_PrivateConfigPacket_SetInfoLabelConfig_SetInfoLabel_InfoLabelAction)(temeshtastic_PrivateConfigPacket_SetInfoLabelConfig_SetInfoLabel_InfoLabelAction_DELETE+1))

#define _temeshtastic_PrivateConfigPacket_EnterBootloader_BootloaderReason_MIN temeshtastic_PrivateConfigPacket_EnterBootloader_BootloaderReason_BOOTLOADER_REASON_UNKNOWN
#define _temeshtastic_PrivateConfigPacket_EnterBootloader_BootloaderReason_MAX temeshtastic_PrivateConfigPacket_EnterBootloader_BootloaderReason_BOOTLOADER_REASON_TEST
#define _temeshtastic_PrivateConfigPacket_EnterBootloader_BootloaderReason_ARRAYSIZE ((temeshtastic_PrivateConfigPacket_EnterBootloader_BootloaderReason)(temeshtastic_PrivateConfigPacket_EnterBootloader_BootloaderReason_BOOTLOADER_REASON_TEST+1))

#define _temeshtastic_PrivateConfigPacket_OperationResult_Operation_MIN temeshtastic_PrivateConfigPacket_OperationResult_Operation_OPERATION_UNKNOWN
#define _temeshtastic_PrivateConfigPacket_OperationResult_Operation_MAX temeshtastic_PrivateConfigPacket_OperationResult_Operation_OPERATION_ENTER_BOOTLOADER
#define _temeshtastic_PrivateConfigPacket_OperationResult_Operation_ARRAYSIZE ((temeshtastic_PrivateConfigPacket_OperationResult_Operation)(temeshtastic_PrivateConfigPacket_OperationResult_Operation_OPERATION_ENTER_BOOTLOADER+1))

#define _temeshtastic_PrivateConfigPacket_OperationResult_Status_MIN temeshtastic_PrivateConfigPacket_OperationResult_Status_STATUS_UNKNOWN
#define _temeshtastic_PrivateConfigPacket_OperationResult_Status_MAX temeshtastic_PrivateConfigPacket_OperationResult_Status_STATUS_UNSUPPORTED
#define _temeshtastic_PrivateConfigPacket_OperationResult_Status_ARRAYSIZE ((temeshtastic_PrivateConfigPacket_OperationResult_Status)(temeshtastic_PrivateConfigPacket_OperationResult_Status_STATUS_UNSUPPORTED+1))


#define temeshtastic_DeviceFactoryIdentity_status_ENUMTYPE temeshtastic_DeviceFactoryIdentity_FactoryIdentityStatus


#define temeshtastic_SyncWakeupConfig_strategy_ENUMTYPE temeshtastic_SyncWakeupConfig_WakeupStrategy














#define temeshtastic_PrivateConfigPacket_SetNetWorkConfig_ResetNetworkConfig_reset_type_ENUMTYPE temeshtastic_PrivateConfigPacket_SetNetWorkConfig_ResetType







#define temeshtastic_PrivateConfigPacket_SetInfoLabelConfig_SetInfoLabel_action_ENUMTYPE temeshtastic_PrivateConfigPacket_SetInfoLabelConfig_SetInfoLabel_InfoLabelAction


#define temeshtastic_PrivateConfigPacket_EnterBootloader_reason_ENUMTYPE temeshtastic_PrivateConfigPacket_EnterBootloader_BootloaderReason


#define temeshtastic_PrivateConfigPacket_OperationResult_operation_ENUMTYPE temeshtastic_PrivateConfigPacket_OperationResult_Operation
#define temeshtastic_PrivateConfigPacket_OperationResult_status_ENUMTYPE temeshtastic_PrivateConfigPacket_OperationResult_Status



/* Initializer values for message structs */
#define temeshtastic_JoinLockAdvertise_init_default {{0, {0}}, 0, 0, ""}
#define temeshtastic_DeviceFactoryIdentity_init_default {0, "", 0, 0, {0, {0}}, 0, _temeshtastic_DeviceFactoryIdentity_FactoryIdentityStatus_MIN, 0, {0, {0}}}
#define temeshtastic_NetWorkConfig_init_default  {{0, {0}}, 0, 0, 0, {0, 0, 0, 0}, {0, {0}}}
#define temeshtastic_SyncWakeupConfig_init_default {0, _temeshtastic_SyncWakeupConfig_WakeupStrategy_MIN, false, temeshtastic_SyncWakeupConfig_FixedWakeup_init_default, false, temeshtastic_SyncWakeupConfig_ScheduledWakeup_init_default, false, temeshtastic_SyncWakeupConfig_WakeupWindow_init_default}
#define temeshtastic_SyncWakeupConfig_TimeSlot_init_default {0, 0, 0, 0}
#define temeshtastic_SyncWakeupConfig_FixedWakeup_init_default {0, 0, 0}
#define temeshtastic_SyncWakeupConfig_ScheduledWakeup_init_default {0, 0, {temeshtastic_SyncWakeupConfig_TimeSlot_init_default, temeshtastic_SyncWakeupConfig_TimeSlot_init_default, temeshtastic_SyncWakeupConfig_TimeSlot_init_default, temeshtastic_SyncWakeupConfig_TimeSlot_init_default}}
#define temeshtastic_SyncWakeupConfig_WakeupWindow_init_default {0, 0, 0, 0, 0, 0}
#define temeshtastic_DeviceLabels_init_default   {0, {temeshtastic_DeviceLabels_InfoLabel_init_default, temeshtastic_DeviceLabels_InfoLabel_init_default, temeshtastic_DeviceLabels_InfoLabel_init_default, temeshtastic_DeviceLabels_InfoLabel_init_default, temeshtastic_DeviceLabels_InfoLabel_init_default, temeshtastic_DeviceLabels_InfoLabel_init_default, temeshtastic_DeviceLabels_InfoLabel_init_default, temeshtastic_DeviceLabels_InfoLabel_init_default, temeshtastic_DeviceLabels_InfoLabel_init_default, temeshtastic_DeviceLabels_InfoLabel_init_default}}
#define temeshtastic_DeviceLabels_InfoLabel_init_default {0, "", ""}
#define temeshtastic_PrivateConfig_init_default  {false, temeshtastic_DeviceFactoryIdentity_init_default, false, temeshtastic_NetWorkConfig_init_default, false, temeshtastic_SyncWakeupConfig_init_default, false, temeshtastic_DeviceLabels_init_default, 0}
#define temeshtastic_PrivateConfigPacket_init_default {0, {temeshtastic_PrivateConfigPacket_DownlinkPacket_init_default}, 0}
#define temeshtastic_PrivateConfigPacket_SetDeviceFactoryIdentity_init_default {0, {0}}
#define temeshtastic_PrivateConfigPacket_SetNetWorkConfig_init_default {0, {0}}
#define temeshtastic_PrivateConfigPacket_SetNetWorkConfig_Channel12Config_init_default {"", {0, {0}}, "", {0, {0}}}
#define temeshtastic_PrivateConfigPacket_SetNetWorkConfig_ChangeNetworkKey_init_default {{0, {0}}, 0, {0, {0}}, {0, {0}}}
#define temeshtastic_PrivateConfigPacket_SetNetWorkConfig_ChangeAdmin_init_default {{0, {0}}, 0, 0, {0, {0}}}
#define temeshtastic_PrivateConfigPacket_SetNetWorkConfig_ResetNetworkConfig_init_default {_temeshtastic_PrivateConfigPacket_SetNetWorkConfig_ResetType_MIN, 0, {0, {0}}}
#define temeshtastic_PrivateConfigPacket_SetNetWorkConfig_TrustedGatewayConfig_init_default {0, 0, {0}}
#define temeshtastic_PrivateConfigPacket_SetNetWorkConfig_JoinNetWorkV2_init_default {{0, {0}}, {0, {0}}, 0, {0, {0}}}
#define temeshtastic_PrivateConfigPacket_SetNetWorkConfig_GatewayAnnounce_init_default {{0, {0}}, {0, {0}}}
#define temeshtastic_PrivateConfigPacket_SetSyncWakeupConfig_init_default {0, {0}}
#define temeshtastic_PrivateConfigPacket_SetSyncWakeupConfig_KeepAwakeRequest_init_default {0}
#define temeshtastic_PrivateConfigPacket_SetInfoLabelConfig_init_default {0, {0}}
#define temeshtastic_PrivateConfigPacket_SetInfoLabelConfig_SetInfoLabel_init_default {_temeshtastic_PrivateConfigPacket_SetInfoLabelConfig_SetInfoLabel_InfoLabelAction_MIN, false, temeshtastic_PrivateConfigPacket_SetInfoLabelConfig_SetInfoLabel_InfoLabel_init_default}
#define temeshtastic_PrivateConfigPacket_SetInfoLabelConfig_SetInfoLabel_InfoLabel_init_default {0, "", ""}
#define temeshtastic_PrivateConfigPacket_EnterBootloader_init_default {_temeshtastic_PrivateConfigPacket_EnterBootloader_BootloaderReason_MIN, 0, {0, {0}}}
#define temeshtastic_PrivateConfigPacket_DownlinkPacket_init_default {0, {temeshtastic_PrivateConfigPacket_SetDeviceFactoryIdentity_init_default}}
#define temeshtastic_PrivateConfigPacket_OperationResult_init_default {_temeshtastic_PrivateConfigPacket_OperationResult_Operation_MIN, _temeshtastic_PrivateConfigPacket_OperationResult_Status_MIN, 0, 0, 0, 0, 0, ""}
#define temeshtastic_PrivateConfigPacket_UplinkPacket_init_default {0, {temeshtastic_DeviceFactoryIdentity_init_default}}
#define temeshtastic_JoinLockAdvertise_init_zero {{0, {0}}, 0, 0, ""}
#define temeshtastic_DeviceFactoryIdentity_init_zero {0, "", 0, 0, {0, {0}}, 0, _temeshtastic_DeviceFactoryIdentity_FactoryIdentityStatus_MIN, 0, {0, {0}}}
#define temeshtastic_NetWorkConfig_init_zero     {{0, {0}}, 0, 0, 0, {0, 0, 0, 0}, {0, {0}}}
#define temeshtastic_SyncWakeupConfig_init_zero  {0, _temeshtastic_SyncWakeupConfig_WakeupStrategy_MIN, false, temeshtastic_SyncWakeupConfig_FixedWakeup_init_zero, false, temeshtastic_SyncWakeupConfig_ScheduledWakeup_init_zero, false, temeshtastic_SyncWakeupConfig_WakeupWindow_init_zero}
#define temeshtastic_SyncWakeupConfig_TimeSlot_init_zero {0, 0, 0, 0}
#define temeshtastic_SyncWakeupConfig_FixedWakeup_init_zero {0, 0, 0}
#define temeshtastic_SyncWakeupConfig_ScheduledWakeup_init_zero {0, 0, {temeshtastic_SyncWakeupConfig_TimeSlot_init_zero, temeshtastic_SyncWakeupConfig_TimeSlot_init_zero, temeshtastic_SyncWakeupConfig_TimeSlot_init_zero, temeshtastic_SyncWakeupConfig_TimeSlot_init_zero}}
#define temeshtastic_SyncWakeupConfig_WakeupWindow_init_zero {0, 0, 0, 0, 0, 0}
#define temeshtastic_DeviceLabels_init_zero      {0, {temeshtastic_DeviceLabels_InfoLabel_init_zero, temeshtastic_DeviceLabels_InfoLabel_init_zero, temeshtastic_DeviceLabels_InfoLabel_init_zero, temeshtastic_DeviceLabels_InfoLabel_init_zero, temeshtastic_DeviceLabels_InfoLabel_init_zero, temeshtastic_DeviceLabels_InfoLabel_init_zero, temeshtastic_DeviceLabels_InfoLabel_init_zero, temeshtastic_DeviceLabels_InfoLabel_init_zero, temeshtastic_DeviceLabels_InfoLabel_init_zero, temeshtastic_DeviceLabels_InfoLabel_init_zero}}
#define temeshtastic_DeviceLabels_InfoLabel_init_zero {0, "", ""}
#define temeshtastic_PrivateConfig_init_zero     {false, temeshtastic_DeviceFactoryIdentity_init_zero, false, temeshtastic_NetWorkConfig_init_zero, false, temeshtastic_SyncWakeupConfig_init_zero, false, temeshtastic_DeviceLabels_init_zero, 0}
#define temeshtastic_PrivateConfigPacket_init_zero {0, {temeshtastic_PrivateConfigPacket_DownlinkPacket_init_zero}, 0}
#define temeshtastic_PrivateConfigPacket_SetDeviceFactoryIdentity_init_zero {0, {0}}
#define temeshtastic_PrivateConfigPacket_SetNetWorkConfig_init_zero {0, {0}}
#define temeshtastic_PrivateConfigPacket_SetNetWorkConfig_Channel12Config_init_zero {"", {0, {0}}, "", {0, {0}}}
#define temeshtastic_PrivateConfigPacket_SetNetWorkConfig_ChangeNetworkKey_init_zero {{0, {0}}, 0, {0, {0}}, {0, {0}}}
#define temeshtastic_PrivateConfigPacket_SetNetWorkConfig_ChangeAdmin_init_zero {{0, {0}}, 0, 0, {0, {0}}}
#define temeshtastic_PrivateConfigPacket_SetNetWorkConfig_ResetNetworkConfig_init_zero {_temeshtastic_PrivateConfigPacket_SetNetWorkConfig_ResetType_MIN, 0, {0, {0}}}
#define temeshtastic_PrivateConfigPacket_SetNetWorkConfig_TrustedGatewayConfig_init_zero {0, 0, {0}}
#define temeshtastic_PrivateConfigPacket_SetNetWorkConfig_JoinNetWorkV2_init_zero {{0, {0}}, {0, {0}}, 0, {0, {0}}}
#define temeshtastic_PrivateConfigPacket_SetNetWorkConfig_GatewayAnnounce_init_zero {{0, {0}}, {0, {0}}}
#define temeshtastic_PrivateConfigPacket_SetSyncWakeupConfig_init_zero {0, {0}}
#define temeshtastic_PrivateConfigPacket_SetSyncWakeupConfig_KeepAwakeRequest_init_zero {0}
#define temeshtastic_PrivateConfigPacket_SetInfoLabelConfig_init_zero {0, {0}}
#define temeshtastic_PrivateConfigPacket_SetInfoLabelConfig_SetInfoLabel_init_zero {_temeshtastic_PrivateConfigPacket_SetInfoLabelConfig_SetInfoLabel_InfoLabelAction_MIN, false, temeshtastic_PrivateConfigPacket_SetInfoLabelConfig_SetInfoLabel_InfoLabel_init_zero}
#define temeshtastic_PrivateConfigPacket_SetInfoLabelConfig_SetInfoLabel_InfoLabel_init_zero {0, "", ""}
#define temeshtastic_PrivateConfigPacket_EnterBootloader_init_zero {_temeshtastic_PrivateConfigPacket_EnterBootloader_BootloaderReason_MIN, 0, {0, {0}}}
#define temeshtastic_PrivateConfigPacket_DownlinkPacket_init_zero {0, {temeshtastic_PrivateConfigPacket_SetDeviceFactoryIdentity_init_zero}}
#define temeshtastic_PrivateConfigPacket_OperationResult_init_zero {_temeshtastic_PrivateConfigPacket_OperationResult_Operation_MIN, _temeshtastic_PrivateConfigPacket_OperationResult_Status_MIN, 0, 0, 0, 0, 0, ""}
#define temeshtastic_PrivateConfigPacket_UplinkPacket_init_zero {0, {temeshtastic_DeviceFactoryIdentity_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define temeshtastic_JoinLockAdvertise_join_challenge_tag 1
#define temeshtastic_JoinLockAdvertise_dev_eui_hi_tag 2
#define temeshtastic_JoinLockAdvertise_dev_eui_lo_tag 3
#define temeshtastic_JoinLockAdvertise_sn_tag    4
#define temeshtastic_DeviceFactoryIdentity_factory_version_tag 1
#define temeshtastic_DeviceFactoryIdentity_sn_tag 2
#define temeshtastic_DeviceFactoryIdentity_dev_eui_hi_tag 3
#define temeshtastic_DeviceFactoryIdentity_dev_eui_lo_tag 4
#define temeshtastic_DeviceFactoryIdentity_device_private_key_tag 5
#define temeshtastic_DeviceFactoryIdentity_manufacturing_timestamp_tag 6
#define temeshtastic_DeviceFactoryIdentity_status_tag 7
#define temeshtastic_DeviceFactoryIdentity_identity_crc_tag 8
#define temeshtastic_DeviceFactoryIdentity_legacy_app_key_tag 9
#define temeshtastic_NetWorkConfig_network_public_key_tag 1
#define temeshtastic_NetWorkConfig_last_change_timestamp_tag 2
#define temeshtastic_NetWorkConfig_is_single_gateway_tag 3
#define temeshtastic_NetWorkConfig_trusted_gateway_sources_tag 4
#define temeshtastic_NetWorkConfig_network_seed_tag 5
#define temeshtastic_SyncWakeupConfig_TimeSlot_start_hour_tag 1
#define temeshtastic_SyncWakeupConfig_TimeSlot_end_hour_tag 2
#define temeshtastic_SyncWakeupConfig_TimeSlot_interval_min_tag 3
#define temeshtastic_SyncWakeupConfig_TimeSlot_align_minute_tag 4
#define temeshtastic_SyncWakeupConfig_FixedWakeup_interval_min_tag 1
#define temeshtastic_SyncWakeupConfig_FixedWakeup_align_minute_tag 2
#define temeshtastic_SyncWakeupConfig_FixedWakeup_offset_sec_tag 3
#define temeshtastic_SyncWakeupConfig_ScheduledWakeup_offset_sec_tag 1
#define temeshtastic_SyncWakeupConfig_ScheduledWakeup_time_slots_tag 2
#define temeshtastic_SyncWakeupConfig_WakeupWindow_startup_delay_sec_tag 1
#define temeshtastic_SyncWakeupConfig_WakeupWindow_random_delay_max_sec_tag 2
#define temeshtastic_SyncWakeupConfig_WakeupWindow_gateway_wait_sec_tag 3
#define temeshtastic_SyncWakeupConfig_WakeupWindow_final_wait_sec_tag 4
#define temeshtastic_SyncWakeupConfig_WakeupWindow_degraded_window_sec_tag 5
#define temeshtastic_SyncWakeupConfig_WakeupWindow_factory_window_sec_tag 6
#define temeshtastic_SyncWakeupConfig_enabled_tag 1
#define temeshtastic_SyncWakeupConfig_strategy_tag 2
#define temeshtastic_SyncWakeupConfig_fixed_wakeup_tag 3
#define temeshtastic_SyncWakeupConfig_scheduled_wakeup_tag 4
#define temeshtastic_SyncWakeupConfig_wakeup_window_tag 5
#define temeshtastic_DeviceLabels_InfoLabel_id_tag 1
#define temeshtastic_DeviceLabels_InfoLabel_key_tag 2
#define temeshtastic_DeviceLabels_InfoLabel_value_tag 3
#define temeshtastic_DeviceLabels_info_labels_tag 1
#define temeshtastic_PrivateConfig_factory_identity_tag 1
#define temeshtastic_PrivateConfig_network_config_tag 2
#define temeshtastic_PrivateConfig_sync_wakeup_tag 3
#define temeshtastic_PrivateConfig_device_labels_tag 4
#define temeshtastic_PrivateConfig_private_version_tag 5
#define temeshtastic_PrivateConfigPacket_SetDeviceFactoryIdentity_get_factory_identity_tag 1
#define temeshtastic_PrivateConfigPacket_SetDeviceFactoryIdentity_factory_identity_tag 2
#define temeshtastic_PrivateConfigPacket_SetNetWorkConfig_Channel12Config_channel1_name_tag 1
#define temeshtastic_PrivateConfigPacket_SetNetWorkConfig_Channel12Config_psk1_tag 2
#define temeshtastic_PrivateConfigPacket_SetNetWorkConfig_Channel12Config_channel2_name_tag 3
#define temeshtastic_PrivateConfigPacket_SetNetWorkConfig_Channel12Config_psk2_tag 4
#define temeshtastic_PrivateConfigPacket_SetNetWorkConfig_ChangeNetworkKey_new_network_public_key_tag 1
#define temeshtastic_PrivateConfigPacket_SetNetWorkConfig_ChangeNetworkKey_timestamp_tag 2
#define temeshtastic_PrivateConfigPacket_SetNetWorkConfig_ChangeNetworkKey_auth_code_tag 3
#define temeshtastic_PrivateConfigPacket_SetNetWorkConfig_ChangeNetworkKey_new_network_seed_tag 4
#define temeshtastic_PrivateConfigPacket_SetNetWorkConfig_ChangeAdmin_new_gateway_public_key_tag 1
#define temeshtastic_PrivateConfigPacket_SetNetWorkConfig_ChangeAdmin_new_gateway_node_id_tag 2
#define temeshtastic_PrivateConfigPacket_SetNetWorkConfig_ChangeAdmin_timestamp_tag 3
#define temeshtastic_PrivateConfigPacket_SetNetWorkConfig_ChangeAdmin_auth_code_tag 4
#define temeshtastic_PrivateConfigPacket_SetNetWorkConfig_ResetNetworkConfig_reset_type_tag 1
#define temeshtastic_PrivateConfigPacket_SetNetWorkConfig_ResetNetworkConfig_timestamp_tag 2
#define temeshtastic_PrivateConfigPacket_SetNetWorkConfig_ResetNetworkConfig_auth_code_tag 3
#define temeshtastic_PrivateConfigPacket_SetNetWorkConfig_TrustedGatewayConfig_is_single_gateway_tag 1
#define temeshtastic_PrivateConfigPacket_SetNetWorkConfig_TrustedGatewayConfig_get_trusted_gateway_list_tag 2
#define temeshtastic_PrivateConfigPacket_SetNetWorkConfig_TrustedGatewayConfig_add_trusted_gateway_tag 3
#define temeshtastic_PrivateConfigPacket_SetNetWorkConfig_TrustedGatewayConfig_remove_trusted_gateway_tag 4
#define temeshtastic_PrivateConfigPacket_SetNetWorkConfig_JoinNetWorkV2_network_public_key_tag 1
#define temeshtastic_PrivateConfigPacket_SetNetWorkConfig_JoinNetWorkV2_network_seed_tag 2
#define temeshtastic_PrivateConfigPacket_SetNetWorkConfig_JoinNetWorkV2_timestamp_tag 3
#define temeshtastic_PrivateConfigPacket_SetNetWorkConfig_JoinNetWorkV2_auth_code_tag 4
#define temeshtastic_PrivateConfigPacket_SetNetWorkConfig_GatewayAnnounce_network_public_key_tag 1
#define temeshtastic_PrivateConfigPacket_SetNetWorkConfig_GatewayAnnounce_auth_code_tag 2
#define temeshtastic_PrivateConfigPacket_SetNetWorkConfig_get_network_config_tag 1
#define temeshtastic_PrivateConfigPacket_SetNetWorkConfig_channel12_config_tag 2
#define temeshtastic_PrivateConfigPacket_SetNetWorkConfig_change_network_key_tag 3
#define temeshtastic_PrivateConfigPacket_SetNetWorkConfig_change_admin_tag 4
#define temeshtastic_PrivateConfigPacket_SetNetWorkConfig_reset_network_config_tag 5
#define temeshtastic_PrivateConfigPacket_SetNetWorkConfig_trusted_gateway_config_tag 6
#define temeshtastic_PrivateConfigPacket_SetNetWorkConfig_join_network_v2_tag 7
#define temeshtastic_PrivateConfigPacket_SetNetWorkConfig_get_join_lock_advertise_tag 8
#define temeshtastic_PrivateConfigPacket_SetNetWorkConfig_gateway_announce_tag 9
#define temeshtastic_PrivateConfigPacket_SetSyncWakeupConfig_KeepAwakeRequest_duration_sec_tag 1
#define temeshtastic_PrivateConfigPacket_SetSyncWakeupConfig_get_sync_wakeup_config_tag 1
#define temeshtastic_PrivateConfigPacket_SetSyncWakeupConfig_config_tag 2
#define temeshtastic_PrivateConfigPacket_SetSyncWakeupConfig_keep_awake_tag 3
#define temeshtastic_PrivateConfigPacket_SetInfoLabelConfig_SetInfoLabel_InfoLabel_id_tag 1
#define temeshtastic_PrivateConfigPacket_SetInfoLabelConfig_SetInfoLabel_InfoLabel_key_tag 2
#define temeshtastic_PrivateConfigPacket_SetInfoLabelConfig_SetInfoLabel_InfoLabel_value_tag 3
#define temeshtastic_PrivateConfigPacket_SetInfoLabelConfig_SetInfoLabel_action_tag 1
#define temeshtastic_PrivateConfigPacket_SetInfoLabelConfig_SetInfoLabel_info_label_tag 2
#define temeshtastic_PrivateConfigPacket_SetInfoLabelConfig_get_info_label_config_tag 1
#define temeshtastic_PrivateConfigPacket_SetInfoLabelConfig_set_info_label_tag 2
#define temeshtastic_PrivateConfigPacket_EnterBootloader_reason_tag 1
#define temeshtastic_PrivateConfigPacket_EnterBootloader_delay_ms_tag 2
#define temeshtastic_PrivateConfigPacket_EnterBootloader_auth_code_tag 3
#define temeshtastic_PrivateConfigPacket_DownlinkPacket_set_factory_identity_tag 1
#define temeshtastic_PrivateConfigPacket_DownlinkPacket_set_network_config_tag 2
#define temeshtastic_PrivateConfigPacket_DownlinkPacket_set_sync_wakeup_config_tag 3
#define temeshtastic_PrivateConfigPacket_DownlinkPacket_set_info_label_config_tag 4
#define temeshtastic_PrivateConfigPacket_DownlinkPacket_enter_bootloader_tag 5
#define temeshtastic_PrivateConfigPacket_OperationResult_operation_tag 1
#define temeshtastic_PrivateConfigPacket_OperationResult_status_tag 2
#define temeshtastic_PrivateConfigPacket_OperationResult_request_id_tag 3
#define temeshtastic_PrivateConfigPacket_OperationResult_target_node_id_tag 4
#define temeshtastic_PrivateConfigPacket_OperationResult_source_node_id_tag 5
#define temeshtastic_PrivateConfigPacket_OperationResult_gateway_node_id_tag 6
#define temeshtastic_PrivateConfigPacket_OperationResult_operation_timestamp_tag 7
#define temeshtastic_PrivateConfigPacket_OperationResult_message_tag 8
#define temeshtastic_PrivateConfigPacket_UplinkPacket_factory_identity_tag 1
#define temeshtastic_PrivateConfigPacket_UplinkPacket_network_config_tag 2
#define temeshtastic_PrivateConfigPacket_UplinkPacket_sync_wakeup_config_tag 3
#define temeshtastic_PrivateConfigPacket_UplinkPacket_device_labels_tag 4
#define temeshtastic_PrivateConfigPacket_UplinkPacket_join_lock_advertise_tag 5
#define temeshtastic_PrivateConfigPacket_UplinkPacket_operation_result_tag 6
#define temeshtastic_PrivateConfigPacket_downlink_packet_tag 1
#define temeshtastic_PrivateConfigPacket_uplink_packet_tag 2
#define temeshtastic_PrivateConfigPacket_label_id_tag 3

/* Struct field encoding specification for nanopb */
#define temeshtastic_JoinLockAdvertise_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BYTES,    join_challenge,    1) \
X(a, STATIC,   SINGULAR, UINT32,   dev_eui_hi,        2) \
X(a, STATIC,   SINGULAR, UINT32,   dev_eui_lo,        3) \
X(a, STATIC,   SINGULAR, STRING,   sn,                4)
#define temeshtastic_JoinLockAdvertise_CALLBACK NULL
#define temeshtastic_JoinLockAdvertise_DEFAULT NULL

#define temeshtastic_DeviceFactoryIdentity_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   factory_version,   1) \
X(a, STATIC,   SINGULAR, STRING,   sn,                2) \
X(a, STATIC,   SINGULAR, UINT32,   dev_eui_hi,        3) \
X(a, STATIC,   SINGULAR, UINT32,   dev_eui_lo,        4) \
X(a, STATIC,   SINGULAR, BYTES,    device_private_key,   5) \
X(a, STATIC,   SINGULAR, UINT64,   manufacturing_timestamp,   6) \
X(a, STATIC,   SINGULAR, UENUM,    status,            7) \
X(a, STATIC,   SINGULAR, UINT32,   identity_crc,      8) \
X(a, STATIC,   SINGULAR, BYTES,    legacy_app_key,    9)
#define temeshtastic_DeviceFactoryIdentity_CALLBACK NULL
#define temeshtastic_DeviceFactoryIdentity_DEFAULT NULL

#define temeshtastic_NetWorkConfig_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BYTES,    network_public_key,   1) \
X(a, STATIC,   SINGULAR, UINT64,   last_change_timestamp,   2) \
X(a, STATIC,   SINGULAR, BOOL,     is_single_gateway,   3) \
X(a, STATIC,   REPEATED, UINT32,   trusted_gateway_sources,   4) \
X(a, STATIC,   SINGULAR, BYTES,    network_seed,      5)
#define temeshtastic_NetWorkConfig_CALLBACK NULL
#define temeshtastic_NetWorkConfig_DEFAULT NULL

#define temeshtastic_SyncWakeupConfig_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     enabled,           1) \
X(a, STATIC,   SINGULAR, UENUM,    strategy,          2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  fixed_wakeup,      3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  scheduled_wakeup,   4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  wakeup_window,     5)
#define temeshtastic_SyncWakeupConfig_CALLBACK NULL
#define temeshtastic_SyncWakeupConfig_DEFAULT NULL
#define temeshtastic_SyncWakeupConfig_fixed_wakeup_MSGTYPE temeshtastic_SyncWakeupConfig_FixedWakeup
#define temeshtastic_SyncWakeupConfig_scheduled_wakeup_MSGTYPE temeshtastic_SyncWakeupConfig_ScheduledWakeup
#define temeshtastic_SyncWakeupConfig_wakeup_window_MSGTYPE temeshtastic_SyncWakeupConfig_WakeupWindow

#define temeshtastic_SyncWakeupConfig_TimeSlot_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   start_hour,        1) \
X(a, STATIC,   SINGULAR, UINT32,   end_hour,          2) \
X(a, STATIC,   SINGULAR, UINT32,   interval_min,      3) \
X(a, STATIC,   SINGULAR, UINT32,   align_minute,      4)
#define temeshtastic_SyncWakeupConfig_TimeSlot_CALLBACK NULL
#define temeshtastic_SyncWakeupConfig_TimeSlot_DEFAULT NULL

#define temeshtastic_SyncWakeupConfig_FixedWakeup_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   interval_min,      1) \
X(a, STATIC,   SINGULAR, UINT32,   align_minute,      2) \
X(a, STATIC,   SINGULAR, UINT32,   offset_sec,        3)
#define temeshtastic_SyncWakeupConfig_FixedWakeup_CALLBACK NULL
#define temeshtastic_SyncWakeupConfig_FixedWakeup_DEFAULT NULL

#define temeshtastic_SyncWakeupConfig_ScheduledWakeup_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   offset_sec,        1) \
X(a, STATIC,   REPEATED, MESSAGE,  time_slots,        2)
#define temeshtastic_SyncWakeupConfig_ScheduledWakeup_CALLBACK NULL
#define temeshtastic_SyncWakeupConfig_ScheduledWakeup_DEFAULT NULL
#define temeshtastic_SyncWakeupConfig_ScheduledWakeup_time_slots_MSGTYPE temeshtastic_SyncWakeupConfig_TimeSlot

#define temeshtastic_SyncWakeupConfig_WakeupWindow_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   startup_delay_sec,   1) \
X(a, STATIC,   SINGULAR, UINT32,   random_delay_max_sec,   2) \
X(a, STATIC,   SINGULAR, UINT32,   gateway_wait_sec,   3) \
X(a, STATIC,   SINGULAR, UINT32,   final_wait_sec,    4) \
X(a, STATIC,   SINGULAR, UINT32,   degraded_window_sec,   5) \
X(a, STATIC,   SINGULAR, UINT32,   factory_window_sec,   6)
#define temeshtastic_SyncWakeupConfig_WakeupWindow_CALLBACK NULL
#define temeshtastic_SyncWakeupConfig_WakeupWindow_DEFAULT NULL

#define temeshtastic_DeviceLabels_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, MESSAGE,  info_labels,       1)
#define temeshtastic_DeviceLabels_CALLBACK NULL
#define temeshtastic_DeviceLabels_DEFAULT NULL
#define temeshtastic_DeviceLabels_info_labels_MSGTYPE temeshtastic_DeviceLabels_InfoLabel

#define temeshtastic_DeviceLabels_InfoLabel_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   id,                1) \
X(a, STATIC,   SINGULAR, STRING,   key,               2) \
X(a, STATIC,   SINGULAR, STRING,   value,             3)
#define temeshtastic_DeviceLabels_InfoLabel_CALLBACK NULL
#define temeshtastic_DeviceLabels_InfoLabel_DEFAULT NULL

#define temeshtastic_PrivateConfig_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  factory_identity,   1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  network_config,    2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  sync_wakeup,       3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  device_labels,     4) \
X(a, STATIC,   SINGULAR, UINT32,   private_version,   5)
#define temeshtastic_PrivateConfig_CALLBACK NULL
#define temeshtastic_PrivateConfig_DEFAULT NULL
#define temeshtastic_PrivateConfig_factory_identity_MSGTYPE temeshtastic_DeviceFactoryIdentity
#define temeshtastic_PrivateConfig_network_config_MSGTYPE temeshtastic_NetWorkConfig
#define temeshtastic_PrivateConfig_sync_wakeup_MSGTYPE temeshtastic_SyncWakeupConfig
#define temeshtastic_PrivateConfig_device_labels_MSGTYPE temeshtastic_DeviceLabels

#define temeshtastic_PrivateConfigPacket_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (packet_type,downlink_packet,packet_type.downlink_packet),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (packet_type,uplink_packet,packet_type.uplink_packet),   2) \
X(a, STATIC,   SINGULAR, UINT32,   label_id,          3)
#define temeshtastic_PrivateConfigPacket_CALLBACK NULL
#define temeshtastic_PrivateConfigPacket_DEFAULT NULL
#define temeshtastic_PrivateConfigPacket_packet_type_downlink_packet_MSGTYPE temeshtastic_PrivateConfigPacket_DownlinkPacket
#define temeshtastic_PrivateConfigPacket_packet_type_uplink_packet_MSGTYPE temeshtastic_PrivateConfigPacket_UplinkPacket

#define temeshtastic_PrivateConfigPacket_SetDeviceFactoryIdentity_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    BOOL,     (payload,get_factory_identity,payload.get_factory_identity),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,factory_identity,payload.factory_identity),   2)
#define temeshtastic_PrivateConfigPacket_SetDeviceFactoryIdentity_CALLBACK NULL
#define temeshtastic_PrivateConfigPacket_SetDeviceFactoryIdentity_DEFAULT NULL
#define temeshtastic_PrivateConfigPacket_SetDeviceFactoryIdentity_payload_factory_identity_MSGTYPE temeshtastic_DeviceFactoryIdentity

#define temeshtastic_PrivateConfigPacket_SetNetWorkConfig_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    BOOL,     (payload,get_network_config,payload.get_network_config),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,channel12_config,payload.channel12_config),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,change_network_key,payload.change_network_key),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,change_admin,payload.change_admin),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,reset_network_config,payload.reset_network_config),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,trusted_gateway_config,payload.trusted_gateway_config),   6) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,join_network_v2,payload.join_network_v2),   7) \
X(a, STATIC,   ONEOF,    BOOL,     (payload,get_join_lock_advertise,payload.get_join_lock_advertise),   8) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,gateway_announce,payload.gateway_announce),   9)
#define temeshtastic_PrivateConfigPacket_SetNetWorkConfig_CALLBACK NULL
#define temeshtastic_PrivateConfigPacket_SetNetWorkConfig_DEFAULT NULL
#define temeshtastic_PrivateConfigPacket_SetNetWorkConfig_payload_channel12_config_MSGTYPE temeshtastic_PrivateConfigPacket_SetNetWorkConfig_Channel12Config
#define temeshtastic_PrivateConfigPacket_SetNetWorkConfig_payload_change_network_key_MSGTYPE temeshtastic_PrivateConfigPacket_SetNetWorkConfig_ChangeNetworkKey
#define temeshtastic_PrivateConfigPacket_SetNetWorkConfig_payload_change_admin_MSGTYPE temeshtastic_PrivateConfigPacket_SetNetWorkConfig_ChangeAdmin
#define temeshtastic_PrivateConfigPacket_SetNetWorkConfig_payload_reset_network_config_MSGTYPE temeshtastic_PrivateConfigPacket_SetNetWorkConfig_ResetNetworkConfig
#define temeshtastic_PrivateConfigPacket_SetNetWorkConfig_payload_trusted_gateway_config_MSGTYPE temeshtastic_PrivateConfigPacket_SetNetWorkConfig_TrustedGatewayConfig
#define temeshtastic_PrivateConfigPacket_SetNetWorkConfig_payload_join_network_v2_MSGTYPE temeshtastic_PrivateConfigPacket_SetNetWorkConfig_JoinNetWorkV2
#define temeshtastic_PrivateConfigPacket_SetNetWorkConfig_payload_gateway_announce_MSGTYPE temeshtastic_PrivateConfigPacket_SetNetWorkConfig_GatewayAnnounce

#define temeshtastic_PrivateConfigPacket_SetNetWorkConfig_Channel12Config_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   channel1_name,     1) \
X(a, STATIC,   SINGULAR, BYTES,    psk1,              2) \
X(a, STATIC,   SINGULAR, STRING,   channel2_name,     3) \
X(a, STATIC,   SINGULAR, BYTES,    psk2,              4)
#define temeshtastic_PrivateConfigPacket_SetNetWorkConfig_Channel12Config_CALLBACK NULL
#define temeshtastic_PrivateConfigPacket_SetNetWorkConfig_Channel12Config_DEFAULT NULL

#define temeshtastic_PrivateConfigPacket_SetNetWorkConfig_ChangeNetworkKey_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BYTES,    new_network_public_key,   1) \
X(a, STATIC,   SINGULAR, UINT64,   timestamp,         2) \
X(a, STATIC,   SINGULAR, BYTES,    auth_code,         3) \
X(a, STATIC,   SINGULAR, BYTES,    new_network_seed,   4)
#define temeshtastic_PrivateConfigPacket_SetNetWorkConfig_ChangeNetworkKey_CALLBACK NULL
#define temeshtastic_PrivateConfigPacket_SetNetWorkConfig_ChangeNetworkKey_DEFAULT NULL

#define temeshtastic_PrivateConfigPacket_SetNetWorkConfig_ChangeAdmin_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BYTES,    new_gateway_public_key,   1) \
X(a, STATIC,   SINGULAR, UINT32,   new_gateway_node_id,   2) \
X(a, STATIC,   SINGULAR, UINT64,   timestamp,         3) \
X(a, STATIC,   SINGULAR, BYTES,    auth_code,         4)
#define temeshtastic_PrivateConfigPacket_SetNetWorkConfig_ChangeAdmin_CALLBACK NULL
#define temeshtastic_PrivateConfigPacket_SetNetWorkConfig_ChangeAdmin_DEFAULT NULL

#define temeshtastic_PrivateConfigPacket_SetNetWorkConfig_ResetNetworkConfig_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    reset_type,        1) \
X(a, STATIC,   SINGULAR, UINT64,   timestamp,         2) \
X(a, STATIC,   SINGULAR, BYTES,    auth_code,         3)
#define temeshtastic_PrivateConfigPacket_SetNetWorkConfig_ResetNetworkConfig_CALLBACK NULL
#define temeshtastic_PrivateConfigPacket_SetNetWorkConfig_ResetNetworkConfig_DEFAULT NULL

#define temeshtastic_PrivateConfigPacket_SetNetWorkConfig_TrustedGatewayConfig_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     is_single_gateway,   1) \
X(a, STATIC,   ONEOF,    BOOL,     (payload,get_trusted_gateway_list,payload.get_trusted_gateway_list),   2) \
X(a, STATIC,   ONEOF,    UINT32,   (payload,add_trusted_gateway,payload.add_trusted_gateway),   3) \
X(a, STATIC,   ONEOF,    UINT32,   (payload,remove_trusted_gateway,payload.remove_trusted_gateway),   4)
#define temeshtastic_PrivateConfigPacket_SetNetWorkConfig_TrustedGatewayConfig_CALLBACK NULL
#define temeshtastic_PrivateConfigPacket_SetNetWorkConfig_TrustedGatewayConfig_DEFAULT NULL

#define temeshtastic_PrivateConfigPacket_SetNetWorkConfig_JoinNetWorkV2_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BYTES,    network_public_key,   1) \
X(a, STATIC,   SINGULAR, BYTES,    network_seed,      2) \
X(a, STATIC,   SINGULAR, UINT64,   timestamp,         3) \
X(a, STATIC,   SINGULAR, BYTES,    auth_code,         4)
#define temeshtastic_PrivateConfigPacket_SetNetWorkConfig_JoinNetWorkV2_CALLBACK NULL
#define temeshtastic_PrivateConfigPacket_SetNetWorkConfig_JoinNetWorkV2_DEFAULT NULL

#define temeshtastic_PrivateConfigPacket_SetNetWorkConfig_GatewayAnnounce_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BYTES,    network_public_key,   1) \
X(a, STATIC,   SINGULAR, BYTES,    auth_code,         2)
#define temeshtastic_PrivateConfigPacket_SetNetWorkConfig_GatewayAnnounce_CALLBACK NULL
#define temeshtastic_PrivateConfigPacket_SetNetWorkConfig_GatewayAnnounce_DEFAULT NULL

#define temeshtastic_PrivateConfigPacket_SetSyncWakeupConfig_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    BOOL,     (payload,get_sync_wakeup_config,payload.get_sync_wakeup_config),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,config,payload.config),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,keep_awake,payload.keep_awake),   3)
#define temeshtastic_PrivateConfigPacket_SetSyncWakeupConfig_CALLBACK NULL
#define temeshtastic_PrivateConfigPacket_SetSyncWakeupConfig_DEFAULT NULL
#define temeshtastic_PrivateConfigPacket_SetSyncWakeupConfig_payload_config_MSGTYPE temeshtastic_SyncWakeupConfig
#define temeshtastic_PrivateConfigPacket_SetSyncWakeupConfig_payload_keep_awake_MSGTYPE temeshtastic_PrivateConfigPacket_SetSyncWakeupConfig_KeepAwakeRequest

#define temeshtastic_PrivateConfigPacket_SetSyncWakeupConfig_KeepAwakeRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   duration_sec,      1)
#define temeshtastic_PrivateConfigPacket_SetSyncWakeupConfig_KeepAwakeRequest_CALLBACK NULL
#define temeshtastic_PrivateConfigPacket_SetSyncWakeupConfig_KeepAwakeRequest_DEFAULT NULL

#define temeshtastic_PrivateConfigPacket_SetInfoLabelConfig_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    BOOL,     (payload,get_info_label_config,payload.get_info_label_config),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,set_info_label,payload.set_info_label),   2)
#define temeshtastic_PrivateConfigPacket_SetInfoLabelConfig_CALLBACK NULL
#define temeshtastic_PrivateConfigPacket_SetInfoLabelConfig_DEFAULT NULL
#define temeshtastic_PrivateConfigPacket_SetInfoLabelConfig_payload_set_info_label_MSGTYPE temeshtastic_PrivateConfigPacket_SetInfoLabelConfig_SetInfoLabel

#define temeshtastic_PrivateConfigPacket_SetInfoLabelConfig_SetInfoLabel_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    action,            1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  info_label,        2)
#define temeshtastic_PrivateConfigPacket_SetInfoLabelConfig_SetInfoLabel_CALLBACK NULL
#define temeshtastic_PrivateConfigPacket_SetInfoLabelConfig_SetInfoLabel_DEFAULT NULL
#define temeshtastic_PrivateConfigPacket_SetInfoLabelConfig_SetInfoLabel_info_label_MSGTYPE temeshtastic_PrivateConfigPacket_SetInfoLabelConfig_SetInfoLabel_InfoLabel

#define temeshtastic_PrivateConfigPacket_SetInfoLabelConfig_SetInfoLabel_InfoLabel_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   id,                1) \
X(a, STATIC,   SINGULAR, STRING,   key,               2) \
X(a, STATIC,   SINGULAR, STRING,   value,             3)
#define temeshtastic_PrivateConfigPacket_SetInfoLabelConfig_SetInfoLabel_InfoLabel_CALLBACK NULL
#define temeshtastic_PrivateConfigPacket_SetInfoLabelConfig_SetInfoLabel_InfoLabel_DEFAULT NULL

#define temeshtastic_PrivateConfigPacket_EnterBootloader_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    reason,            1) \
X(a, STATIC,   SINGULAR, UINT32,   delay_ms,          2) \
X(a, STATIC,   SINGULAR, BYTES,    auth_code,         3)
#define temeshtastic_PrivateConfigPacket_EnterBootloader_CALLBACK NULL
#define temeshtastic_PrivateConfigPacket_EnterBootloader_DEFAULT NULL

#define temeshtastic_PrivateConfigPacket_DownlinkPacket_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,set_factory_identity,payload.set_factory_identity),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,set_network_config,payload.set_network_config),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,set_sync_wakeup_config,payload.set_sync_wakeup_config),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,set_info_label_config,payload.set_info_label_config),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,enter_bootloader,payload.enter_bootloader),   5)
#define temeshtastic_PrivateConfigPacket_DownlinkPacket_CALLBACK NULL
#define temeshtastic_PrivateConfigPacket_DownlinkPacket_DEFAULT NULL
#define temeshtastic_PrivateConfigPacket_DownlinkPacket_payload_set_factory_identity_MSGTYPE temeshtastic_PrivateConfigPacket_SetDeviceFactoryIdentity
#define temeshtastic_PrivateConfigPacket_DownlinkPacket_payload_set_network_config_MSGTYPE temeshtastic_PrivateConfigPacket_SetNetWorkConfig
#define temeshtastic_PrivateConfigPacket_DownlinkPacket_payload_set_sync_wakeup_config_MSGTYPE temeshtastic_PrivateConfigPacket_SetSyncWakeupConfig
#define temeshtastic_PrivateConfigPacket_DownlinkPacket_payload_set_info_label_config_MSGTYPE temeshtastic_PrivateConfigPacket_SetInfoLabelConfig
#define temeshtastic_PrivateConfigPacket_DownlinkPacket_payload_enter_bootloader_MSGTYPE temeshtastic_PrivateConfigPacket_EnterBootloader

#define temeshtastic_PrivateConfigPacket_OperationResult_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    operation,         1) \
X(a, STATIC,   SINGULAR, UENUM,    status,            2) \
X(a, STATIC,   SINGULAR, UINT32,   request_id,        3) \
X(a, STATIC,   SINGULAR, UINT32,   target_node_id,    4) \
X(a, STATIC,   SINGULAR, UINT32,   source_node_id,    5) \
X(a, STATIC,   SINGULAR, UINT32,   gateway_node_id,   6) \
X(a, STATIC,   SINGULAR, UINT64,   operation_timestamp,   7) \
X(a, STATIC,   SINGULAR, STRING,   message,           8)
#define temeshtastic_PrivateConfigPacket_OperationResult_CALLBACK NULL
#define temeshtastic_PrivateConfigPacket_OperationResult_DEFAULT NULL

#define temeshtastic_PrivateConfigPacket_UplinkPacket_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,factory_identity,payload.factory_identity),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,network_config,payload.network_config),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,sync_wakeup_config,payload.sync_wakeup_config),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,device_labels,payload.device_labels),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,join_lock_advertise,payload.join_lock_advertise),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,operation_result,payload.operation_result),   6)
#define temeshtastic_PrivateConfigPacket_UplinkPacket_CALLBACK NULL
#define temeshtastic_PrivateConfigPacket_UplinkPacket_DEFAULT NULL
#define temeshtastic_PrivateConfigPacket_UplinkPacket_payload_factory_identity_MSGTYPE temeshtastic_DeviceFactoryIdentity
#define temeshtastic_PrivateConfigPacket_UplinkPacket_payload_network_config_MSGTYPE temeshtastic_NetWorkConfig
#define temeshtastic_PrivateConfigPacket_UplinkPacket_payload_sync_wakeup_config_MSGTYPE temeshtastic_SyncWakeupConfig
#define temeshtastic_PrivateConfigPacket_UplinkPacket_payload_device_labels_MSGTYPE temeshtastic_DeviceLabels
#define temeshtastic_PrivateConfigPacket_UplinkPacket_payload_join_lock_advertise_MSGTYPE temeshtastic_JoinLockAdvertise
#define temeshtastic_PrivateConfigPacket_UplinkPacket_payload_operation_result_MSGTYPE temeshtastic_PrivateConfigPacket_OperationResult

extern const pb_msgdesc_t temeshtastic_JoinLockAdvertise_msg;
extern const pb_msgdesc_t temeshtastic_DeviceFactoryIdentity_msg;
extern const pb_msgdesc_t temeshtastic_NetWorkConfig_msg;
extern const pb_msgdesc_t temeshtastic_SyncWakeupConfig_msg;
extern const pb_msgdesc_t temeshtastic_SyncWakeupConfig_TimeSlot_msg;
extern const pb_msgdesc_t temeshtastic_SyncWakeupConfig_FixedWakeup_msg;
extern const pb_msgdesc_t temeshtastic_SyncWakeupConfig_ScheduledWakeup_msg;
extern const pb_msgdesc_t temeshtastic_SyncWakeupConfig_WakeupWindow_msg;
extern const pb_msgdesc_t temeshtastic_DeviceLabels_msg;
extern const pb_msgdesc_t temeshtastic_DeviceLabels_InfoLabel_msg;
extern const pb_msgdesc_t temeshtastic_PrivateConfig_msg;
extern const pb_msgdesc_t temeshtastic_PrivateConfigPacket_msg;
extern const pb_msgdesc_t temeshtastic_PrivateConfigPacket_SetDeviceFactoryIdentity_msg;
extern const pb_msgdesc_t temeshtastic_PrivateConfigPacket_SetNetWorkConfig_msg;
extern const pb_msgdesc_t temeshtastic_PrivateConfigPacket_SetNetWorkConfig_Channel12Config_msg;
extern const pb_msgdesc_t temeshtastic_PrivateConfigPacket_SetNetWorkConfig_ChangeNetworkKey_msg;
extern const pb_msgdesc_t temeshtastic_PrivateConfigPacket_SetNetWorkConfig_ChangeAdmin_msg;
extern const pb_msgdesc_t temeshtastic_PrivateConfigPacket_SetNetWorkConfig_ResetNetworkConfig_msg;
extern const pb_msgdesc_t temeshtastic_PrivateConfigPacket_SetNetWorkConfig_TrustedGatewayConfig_msg;
extern const pb_msgdesc_t temeshtastic_PrivateConfigPacket_SetNetWorkConfig_JoinNetWorkV2_msg;
extern const pb_msgdesc_t temeshtastic_PrivateConfigPacket_SetNetWorkConfig_GatewayAnnounce_msg;
extern const pb_msgdesc_t temeshtastic_PrivateConfigPacket_SetSyncWakeupConfig_msg;
extern const pb_msgdesc_t temeshtastic_PrivateConfigPacket_SetSyncWakeupConfig_KeepAwakeRequest_msg;
extern const pb_msgdesc_t temeshtastic_PrivateConfigPacket_SetInfoLabelConfig_msg;
extern const pb_msgdesc_t temeshtastic_PrivateConfigPacket_SetInfoLabelConfig_SetInfoLabel_msg;
extern const pb_msgdesc_t temeshtastic_PrivateConfigPacket_SetInfoLabelConfig_SetInfoLabel_InfoLabel_msg;
extern const pb_msgdesc_t temeshtastic_PrivateConfigPacket_EnterBootloader_msg;
extern const pb_msgdesc_t temeshtastic_PrivateConfigPacket_DownlinkPacket_msg;
extern const pb_msgdesc_t temeshtastic_PrivateConfigPacket_OperationResult_msg;
extern const pb_msgdesc_t temeshtastic_PrivateConfigPacket_UplinkPacket_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define temeshtastic_JoinLockAdvertise_fields &temeshtastic_JoinLockAdvertise_msg
#define temeshtastic_DeviceFactoryIdentity_fields &temeshtastic_DeviceFactoryIdentity_msg
#define temeshtastic_NetWorkConfig_fields &temeshtastic_NetWorkConfig_msg
#define temeshtastic_SyncWakeupConfig_fields &temeshtastic_SyncWakeupConfig_msg
#define temeshtastic_SyncWakeupConfig_TimeSlot_fields &temeshtastic_SyncWakeupConfig_TimeSlot_msg
#define temeshtastic_SyncWakeupConfig_FixedWakeup_fields &temeshtastic_SyncWakeupConfig_FixedWakeup_msg
#define temeshtastic_SyncWakeupConfig_ScheduledWakeup_fields &temeshtastic_SyncWakeupConfig_ScheduledWakeup_msg
#define temeshtastic_SyncWakeupConfig_WakeupWindow_fields &temeshtastic_SyncWakeupConfig_WakeupWindow_msg
#define temeshtastic_DeviceLabels_fields &temeshtastic_DeviceLabels_msg
#define temeshtastic_DeviceLabels_InfoLabel_fields &temeshtastic_DeviceLabels_InfoLabel_msg
#define temeshtastic_PrivateConfig_fields &temeshtastic_PrivateConfig_msg
#define temeshtastic_PrivateConfigPacket_fields &temeshtastic_PrivateConfigPacket_msg
#define temeshtastic_PrivateConfigPacket_SetDeviceFactoryIdentity_fields &temeshtastic_PrivateConfigPacket_SetDeviceFactoryIdentity_msg
#define temeshtastic_PrivateConfigPacket_SetNetWorkConfig_fields &temeshtastic_PrivateConfigPacket_SetNetWorkConfig_msg
#define temeshtastic_PrivateConfigPacket_SetNetWorkConfig_Channel12Config_fields &temeshtastic_PrivateConfigPacket_SetNetWorkConfig_Channel12Config_msg
#define temeshtastic_PrivateConfigPacket_SetNetWorkConfig_ChangeNetworkKey_fields &temeshtastic_PrivateConfigPacket_SetNetWorkConfig_ChangeNetworkKey_msg
#define temeshtastic_PrivateConfigPacket_SetNetWorkConfig_ChangeAdmin_fields &temeshtastic_PrivateConfigPacket_SetNetWorkConfig_ChangeAdmin_msg
#define temeshtastic_PrivateConfigPacket_SetNetWorkConfig_ResetNetworkConfig_fields &temeshtastic_PrivateConfigPacket_SetNetWorkConfig_ResetNetworkConfig_msg
#define temeshtastic_PrivateConfigPacket_SetNetWorkConfig_TrustedGatewayConfig_fields &temeshtastic_PrivateConfigPacket_SetNetWorkConfig_TrustedGatewayConfig_msg
#define temeshtastic_PrivateConfigPacket_SetNetWorkConfig_JoinNetWorkV2_fields &temeshtastic_PrivateConfigPacket_SetNetWorkConfig_JoinNetWorkV2_msg
#define temeshtastic_PrivateConfigPacket_SetNetWorkConfig_GatewayAnnounce_fields &temeshtastic_PrivateConfigPacket_SetNetWorkConfig_GatewayAnnounce_msg
#define temeshtastic_PrivateConfigPacket_SetSyncWakeupConfig_fields &temeshtastic_PrivateConfigPacket_SetSyncWakeupConfig_msg
#define temeshtastic_PrivateConfigPacket_SetSyncWakeupConfig_KeepAwakeRequest_fields &temeshtastic_PrivateConfigPacket_SetSyncWakeupConfig_KeepAwakeRequest_msg
#define temeshtastic_PrivateConfigPacket_SetInfoLabelConfig_fields &temeshtastic_PrivateConfigPacket_SetInfoLabelConfig_msg
#define temeshtastic_PrivateConfigPacket_SetInfoLabelConfig_SetInfoLabel_fields &temeshtastic_PrivateConfigPacket_SetInfoLabelConfig_SetInfoLabel_msg
#define temeshtastic_PrivateConfigPacket_SetInfoLabelConfig_SetInfoLabel_InfoLabel_fields &temeshtastic_PrivateConfigPacket_SetInfoLabelConfig_SetInfoLabel_InfoLabel_msg
#define temeshtastic_PrivateConfigPacket_EnterBootloader_fields &temeshtastic_PrivateConfigPacket_EnterBootloader_msg
#define temeshtastic_PrivateConfigPacket_DownlinkPacket_fields &temeshtastic_PrivateConfigPacket_DownlinkPacket_msg
#define temeshtastic_PrivateConfigPacket_OperationResult_fields &temeshtastic_PrivateConfigPacket_OperationResult_msg
#define temeshtastic_PrivateConfigPacket_UplinkPacket_fields &temeshtastic_PrivateConfigPacket_UplinkPacket_msg

/* Maximum encoded size of messages (where known) */
#define TEMESHTASTIC_PROTOBUF_PRIVATECONFIG_PB_H_MAX_SIZE temeshtastic_PrivateConfig_size
#define temeshtastic_DeviceFactoryIdentity_size  110
#define temeshtastic_DeviceLabels_InfoLabel_size 48
#define temeshtastic_DeviceLabels_size           500
#define temeshtastic_JoinLockAdvertise_size      51
#define temeshtastic_NetWorkConfig_size          105
#define temeshtastic_PrivateConfigPacket_DownlinkPacket_size 180
#define temeshtastic_PrivateConfigPacket_EnterBootloader_size 42
#define temeshtastic_PrivateConfigPacket_OperationResult_size 88
#define temeshtastic_PrivateConfigPacket_SetDeviceFactoryIdentity_size 112
#define temeshtastic_PrivateConfigPacket_SetInfoLabelConfig_SetInfoLabel_InfoLabel_size 48
#define temeshtastic_PrivateConfigPacket_SetInfoLabelConfig_SetInfoLabel_size 52
#define temeshtastic_PrivateConfigPacket_SetInfoLabelConfig_size 54
#define temeshtastic_PrivateConfigPacket_SetNetWorkConfig_ChangeAdmin_size 85
#define temeshtastic_PrivateConfigPacket_SetNetWorkConfig_ChangeNetworkKey_size 113
#define temeshtastic_PrivateConfigPacket_SetNetWorkConfig_Channel12Config_size 110
#define temeshtastic_PrivateConfigPacket_SetNetWorkConfig_GatewayAnnounce_size 68
#define temeshtastic_PrivateConfigPacket_SetNetWorkConfig_JoinNetWorkV2_size 113
#define temeshtastic_PrivateConfigPacket_SetNetWorkConfig_ResetNetworkConfig_size 47
#define temeshtastic_PrivateConfigPacket_SetNetWorkConfig_TrustedGatewayConfig_size 8
#define temeshtastic_PrivateConfigPacket_SetNetWorkConfig_size 115
#define temeshtastic_PrivateConfigPacket_SetSyncWakeupConfig_KeepAwakeRequest_size 6
#define temeshtastic_PrivateConfigPacket_SetSyncWakeupConfig_size 177
#define temeshtastic_PrivateConfigPacket_UplinkPacket_size 503
#define temeshtastic_PrivateConfigPacket_size    512
#define temeshtastic_PrivateConfig_size          905
#define temeshtastic_SyncWakeupConfig_FixedWakeup_size 18
#define temeshtastic_SyncWakeupConfig_ScheduledWakeup_size 110
#define temeshtastic_SyncWakeupConfig_TimeSlot_size 24
#define temeshtastic_SyncWakeupConfig_WakeupWindow_size 36
#define temeshtastic_SyncWakeupConfig_size       174

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
