[dragino_native_base]
extends = portduino_base
build_flags = ${portduino_base.build_flags} -I variants/native/dragino-linux-gateway
  -I /usr/include
board = cross_platform
board_level = extra
lib_deps = 
  ${portduino_base.lib_deps}
  melopero/Melopero RV3028@^1.1.0

build_src_filter = ${portduino_base.build_src_filter}

[env:dragino-linux-gateway]
extends = dragino_native_base
; The pkg-config commands below optionally add link flags.
; the || : is just a "or run the null command" to avoid returning an error code
build_flags = ${dragino_native_base.build_flags}
  !pkg-config --libs libulfius --silence-errors || :
  !pkg-config --libs openssl --silence-errors || :
  !pkg-config --cflags --libs sdl2 --silence-errors || :
  !pkg-config --cflags --libs libbsd-overlay --silence-errors || :
  -DDRAGINO=1
  -DDRAGINO_GATEWAY=1
  -DDRAGINO_LINUX=1

[env:dragino-linux-gateway-tft]
extends = dragino_native_base
build_type = release
lib_deps =
  ${dragino_native_base.lib_deps}
  ${device-ui_base.lib_deps}
build_flags = ${dragino_native_base.build_flags} -Os -lX11 -linput -lxkbcommon -ffunction-sections -fdata-sections -Wl,--gc-sections
  -D RAM_SIZE=16384
  -D USE_X11=1
  -D HAS_TFT=1
  -D HAS_SCREEN=1
  -D LV_CACHE_DEF_SIZE=6291456
  -D LV_BUILD_TEST=0
  -D LV_USE_LIBINPUT=1
  -D LV_LVGL_H_INCLUDE_SIMPLE
  -D LV_CONF_INCLUDE_SIMPLE
  -D LV_COMP_CONF_INCLUDE_SIMPLE
  -D USE_LOG_DEBUG
  -D LOG_DEBUG_INC=\"DebugConfiguration.h\"
  -D USE_PACKET_API
  -D VIEW_320x240
  !pkg-config --libs libulfius --silence-errors || :
  !pkg-config --libs openssl --silence-errors || :
  !pkg-config --cflags --libs sdl2 --silence-errors || :
  !pkg-config --cflags --libs libbsd-overlay --silence-errors || :
  -DDRAGINO=1
  -DDRAGINO_GATEWAY=1
  -DDRAGINO_LINUX=1
build_src_filter =
  ${dragino_native_base.build_src_filter}
